// Generated by cs2-sdk — https://cs2-sdk.com
#pragma once

#include <cstdint>
#include <windows.h>
#include "../offsets/offsets.hpp"
#include "../schemas/client_dll.hpp"

namespace entity { inline constexpr std::uint32_t CS2_BUILD = 14183; }

struct CGameEntitySystem {
    // Offset of the entity-list chunk-pointer array within CGameEntitySystem.
    static constexpr std::size_t kEntityListOffset = 0x10;
    static constexpr std::size_t kIdentityStride    = 0x70;
    static constexpr int          kChunkSize         = 512;
    static constexpr int          kMaxEntities       = 32768;

    static int GetHighestEntityIndex() noexcept {
        auto client = reinterpret_cast<uintptr_t>(GetModuleHandleA("client.dll"));
        if (!client) return 0;
        auto es = *reinterpret_cast<uintptr_t*>(client + offsets::client::GameEntitySystem);
        if (!es) return 0;
        return *reinterpret_cast<int*>(es + offsets::client::GameEntitySystem_highestEntityIndex);
    }

    static client::CCSPlayerController* GetLocalPlayer() noexcept {
        auto client = reinterpret_cast<uintptr_t>(GetModuleHandleA("client.dll"));
        if (!client) return nullptr;
        return *reinterpret_cast<client::CCSPlayerController**>(client + offsets::client::LocalPlayerController);
    }

    static client::CEntityIdentity* GetIdentityByIndex(int index) noexcept {
        if (index < 0) return nullptr;
        auto client = reinterpret_cast<uintptr_t>(GetModuleHandleA("client.dll"));
        if (!client) return nullptr;
        auto entity_system = *reinterpret_cast<uintptr_t*>(client + offsets::client::GameEntitySystem);
        if (!entity_system) return nullptr;
        auto chunk = *reinterpret_cast<uintptr_t*>(entity_system + kEntityListOffset + static_cast<std::size_t>(index / kChunkSize) * 8);
        if (!chunk) return nullptr;
        return reinterpret_cast<client::CEntityIdentity*>(chunk + static_cast<std::size_t>(index % kChunkSize) * kIdentityStride);
    }

    static void* GetEntityByIndex(int index) noexcept {
        if (index < 0 || index >= kMaxEntities) return nullptr;
        auto* identity = GetIdentityByIndex(index);
        if (!identity) return nullptr;
        return *reinterpret_cast<void**>(identity); // m_pEntity at offset 0x0
    }

    static const char* GetDesignerName(int index) noexcept {
        auto* identity = GetIdentityByIndex(index);
        if (!identity || !GetEntityByIndex(index)) return nullptr;
        return *reinterpret_cast<const char**>(&identity->m_designerName());
    }

    static bool IsPlayerPawn(uint16_t entity_index) noexcept {
        for (int i = 1; i <= 64; ++i) {
            auto* controller = reinterpret_cast<client::CCSPlayerController*>(GetEntityByIndex(i));
            if (!controller || reinterpret_cast<uintptr_t>(controller) <= 0x10000) continue;
            if (controller->m_iTeamNum() != 2 && controller->m_iTeamNum() != 3) continue;
            if (controller->m_hPawn().GetIndex() == entity_index) return true;
        }
        return false;
    }

};

