// Generated by cs2-sdk — https://cs2-sdk.com
//
// Shared macro definitions used by every generated SDK header.
// Include this file (directly or transitively) before any sdk/<module>.hpp.

#pragma once

// Prevent Windows.h min/max macros from interfering with field names
#ifndef NOMINMAX
#define NOMINMAX
#endif

// Undefine min/max macros if they were defined before this header
#ifdef min
#undef min
#endif
#ifdef max
#undef max
#endif

#include <cstddef>
#include <cstdint>
#include <utility>



// ============================================================================
// Source 2 Engine Type Aliases
// ============================================================================
// These types are used throughout the Source 2 schema but aren't defined
// in the engine headers. We provide minimal type aliases here so the SDK
// compiles standalone.

// Basic type aliases that Source 2 uses instead of stdint types
using int8 = std::int8_t;
using int16 = std::int16_t;
using int32 = std::int32_t;
using int64 = std::int64_t;
using uint8 = std::uint8_t;
using uint16 = std::uint16_t;
using uint32 = std::uint32_t;
using uint64 = std::uint64_t;
using float32 = float;
using float64 = double;

// Time-related types
using GameTime_t = float;
using GameTick_t = std::int32_t;

// Symbol/ID types - these are typically just integers or small structs
using PulseSymbol_t = std::uint64_t;
using PulseDocNodeID_t = std::uint32_t;
using PulseRuntimeChunkIndex_t = std::int32_t;
using PulseRegisterMap_t = std::uint64_t;
using WorldGroupId_t = std::uint32_t;
using ChangeAccessorFieldPathIndex_t = std::int32_t;

// Handle types - typically 32-bit indices
template <typename T>
struct CHandle {
    std::uint32_t m_Handle;

    std::uint32_t GetIndex() const noexcept { return m_Handle & 0x7FFF; }
    bool IsValid() const noexcept { return m_Handle != 0xFFFFFFFF; }
};
static_assert(sizeof(CHandle<int>) == 4, "CHandle must be 4 bytes");

template <typename T>
using CStrongHandle = std::uint64_t;

// Container types - forward declarations with minimal implementation
template <typename T, typename A = void*>
class CUtlVector {
public:
    T* m_pElements;
    int m_Size;
    int m_Capacity;
};

template <typename T>
class CUtlLeanVector {
public:
    T* m_pElements;
    int m_Size;
};

template <typename T, int N>
class CUtlVectorFixedGrowable {
public:
    T m_Elements[N];
    int m_Size;
};

template <typename K, typename V, typename L = void*>
class CUtlOrderedMap {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

template <typename K, typename V = K, typename H = void*, typename E = void*>
class CUtlHashtable {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

// Animation network variable wrapper
template <typename T>
class CAnimNetVar {
public:
    T m_Value;
};

// Animation value wrapper
template <typename T>
class CAnimValue {
public:
    T m_Value;
};

// Network variable embedded vector - used for networked arrays
template <typename T, typename A = void*>
class CUtlVectorEmbeddedNetworkVar {
public:
    T* m_pElements;
    int m_Size;
    int m_Capacity;
};

// Alias for single-parameter version
template <typename T>
using C_UtlVectorEmbeddedNetworkVar = CUtlVectorEmbeddedNetworkVar<T>;

// Network variable base vector - used for networked arrays
template <typename T, typename A = void*>
class CNetworkUtlVectorBase {
public:
    T* m_pElements;
    int m_Size;
};

// Alias for single-parameter version
template <typename T>
using C_NetworkUtlVectorBase = CNetworkUtlVectorBase<T>;

// Network variable chainer - used for network variable change tracking
class CNetworkVarChainer {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

// String types - forward declarations
class CUtlString {
public:
    const char* m_pString;
};

class CUtlSymbolLarge {
public:
    std::uint64_t m_Id;
};

class CUtlBinaryBlock {
public:
    void* m_pData;
    int m_Size;
};

class CBufferString {
public:
    char m_buffer[256]; // Placeholder size
};

// Generic template wrappers referenced by schema
template <typename T>
class CVariantBase {
};

template <typename T>
class CAnimScriptParam {
};

template <typename T>
class CResourcePointer {
};

template <typename T>
class CResourceArray {
};

// Additional core types commonly referenced by schema
class Attribute_t {
public:
    std::uint8_t m_Data[16];
};

class CUtlSymbol {
public:
    std::uint32_t m_Id;
};

class CUtlStringTokenWithStorage {
public:
    std::uint64_t m_Id;
};

class CResourceString {
public:
    const char* m_pString;
};

class KeyValues {
public:
    void* m_pData;
};

class CEntityNameString {
public:
    const char* m_pString;
};

class CEntityKeyValues {
public:
    void* m_pData;
};

class IPhysicsJoint {
public:
    void* m_pData;
};

// Cross-module types referenced by client headers
class CBaseAnimGraphDestructibleParts_GraphController {
public:
    std::uint8_t m_Data[8];
};

class CEntityAttributeTable {
public:
    std::uint8_t m_Data[8];
};

class CNetworkTransmitComponent {
public:
    std::uint8_t m_Data[8];
};

class thinkfunc_t {
public:
    std::uint8_t m_Data[8];
};

class CNetworkVelocityVector {
public:
    std::uint8_t m_Data[8];
};

class CParticleProperty {
public:
    std::uint8_t m_Data[8];
};

// Types referenced by runtime schemas but never defined by the schema system
// (forward-only / non-schema engine types). The auto forward-decl pass also
// covers these, but declaring them in the stable base keeps the SDK compiling
// even if a dump is generated by an older binary.
class CModelMaterialGroupName;
namespace rendersystemdx11 { class RenderPrimitiveType_t; }

// Forward-declare common server-owned types in the proper namespace so
// client headers can reference them as ::server::Type without
// requiring the server header to be included first.
namespace server {
    class CBaseAnimGraph;
    class CBaseFilter;
    class CEntityComponent;
    class CLogicalEntity;
    class CBaseProp;
    class CAttributeManager;
    class CSkeletonAnimationController;
    class CBaseAnimGraphDestructibleParts_GraphController;
    class CBaseAnimGraphVariationUserData;
}

enum class TakeDamageFlags_t : std::uint64_t {};
enum class EntityPlatformTypes_t : std::uint8_t {};
enum class MoveCollide_t : std::uint8_t {};
enum class MoveType_t : std::uint8_t {};
enum class BloodType : std::int32_t {};

struct PulseCursorID_t {
    std::uint32_t m_Id;
};

struct ParticleParamID_t {
    std::uint32_t m_Id;
};

enum class PhysInterfaceId_t : std::uint32_t {};

enum class CCSPlayerAnimationState_MoveType_t : std::uint8_t {};
enum class CCSPlayerAnimationState_GroundMoveState_t : std::uint8_t {};
enum class CCSPlayerAnimationState_Direction_t : std::uint8_t {};
enum class CCSPlayerAnimationState_AirAction_t : std::uint8_t {};

struct fltx4 {
    std::uint32_t v[4];
};

struct RotationVector {
    float x, y, z;
};

struct RadianEuler {
    float x, y, z;
};

struct DegreeEuler {
    float x, y, z;
};

// Smart pointer types
template <typename T>
class CSmartPtr {
public:
    T* m_pData;
};

// Relative array type
template <typename T>
class CRelativeArray {
public:
    std::int32_t m_nOffset;
    std::int32_t m_nCount;
};

// Lean vector with fixed growable size
template <typename T, int N>
class CUtlLeanVectorFixedGrowable {
public:
    T m_Elements[N];
    int m_Size;
    int m_Capacity;
};

// Math types - forward declarations
struct Vector {
    float x, y, z;
};

struct Vector2D {
    float x, y;
};

struct Vector4D {
    float x, y, z, w;
};

struct QAngle {
    float x, y, z;
};

struct Quaternion {
    float x, y, z, w;
};

struct matrix3x4_t {
    float m[3][4];
};

struct matrix3x4a_t {
    float m[3][4];
};

struct Color {
    std::uint8_t r, g, b, a;
};

struct AABB_t {
    Vector m_vMinBounds;
    Vector m_vMaxBounds;
};

// Rendering types
struct CRenderBufferBinding {
    std::uint64_t m_hBuffer;
    std::uint32_t m_nBindOffsetBytes;
};

// Additional Source 2 types
class CGlobalSymbol {
public:
    std::uint64_t m_Id;
};

class CColorGradient {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

class CPiecewiseCurve {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

class KeyValues3 {
public:
    void* m_pData;
};

// Material/Rendering descriptor types
struct CMaterialDrawDescriptor {
    std::uint8_t m_Data[128]; // Placeholder
};

struct CMeshletDescriptor {
    std::uint8_t m_Data[64]; // Placeholder
};

struct RTProxyDrawDescriptor_t {
    std::uint8_t m_Data[64]; // Placeholder
};

// Resource handle types - these are typically used for loading game resources
class InfoForResourceTypeIPulseGraphDef {};
class InfoForResourceTypeCModel {};
class InfoForResourceTypeCRenderMesh {};
class InfoForResourceTypeCCompositeMaterialKit {};
class InfoForResourceTypeCCompositeMaterial {};
class InfoForResourceTypeCNmSkeleton {};
class InfoForResourceTypeIMaterial2 {};
class InfoForResourceTypeIParticleSystemDefinition {};
class InfoForResourceTypeIParticleSnapshot {};
class InfoForResourceTypeCNmGraphDefinition {};
class InfoForResourceTypeCNmClip {};
class InfoForResourceTypeCEntityLump {};
class InfoForResourceTypeCChoreoSceneResource {};
class InfoForResourceTypeCPostProcessingResource {};

// Strong handle void type
using CStrongHandleVoid = std::uint64_t;

// Strong handle copyable template - used for resource handles that can be copied
template <typename T>
class CStrongHandleCopyable {
public:
    std::uint64_t m_hHandle;
};

// Weak handle template - used for weak references to resources
template <typename T>
class CWeakHandle {
public:
    std::uint64_t m_hHandle;
};

// Resource name typed template - used for typed resource names
template <typename T>
class CResourceNameTyped {
public:
    std::uint64_t m_nHashCode;
};

// Additional type aliases for animation system
using QuaternionStorage = Quaternion;
using VectorWS = Vector;
using VectorAligned = Vector;

// Additional forward declarations for Source 2 types
class CAnimParamHandle {
public:
    std::uint16_t m_Index;
};

class CAnimInputDamping {
public:
    float m_flSpeedFunction;
    float m_flSpeedScale;
};

class CTransform {
public:
    Vector m_vPosition;
    Quaternion m_orientation;
};

class CNmTarget {
public:
    std::uint8_t m_Data[48]; // Placeholder
};

class CParticleNamedValueRef {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

class CPulseValueFullType {
public:
    std::uint8_t m_Data[24]; // Placeholder
};

class CPulse_Variable {
public:
    std::uint8_t m_Data[32]; // Placeholder
};

class CPulse_PublicOutput {
public:
    std::uint8_t m_Data[32]; // Placeholder
};

class CPulse_Constant {
public:
    std::uint8_t m_Data[32]; // Placeholder
};

class CPulse_DomainValue {
public:
    std::uint8_t m_Data[32]; // Placeholder
};

class CPulse_Chunk {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

class CPulseCell_Base {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

class CPulse_InvokeBinding {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

class CPulse_CallInfo {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

class CPulse_BlackboardReference {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

class CPulse_OutputConnection {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

class CPulse_OutflowConnection {
public:
    std::uint8_t m_Data[72]; // Placeholder
};

class CPulse_ResumePoint {
public:
    std::uint8_t m_Data[72]; // Placeholder
};

class CPulseRuntimeMethodArg {
public:
    std::uint8_t m_Data[32]; // Placeholder
};

// Additional type aliases
using PulseRuntimeCellIndex_t = std::int32_t;
using PulseRuntimeBlackboardReferenceIndex_t = std::int16_t;
using PulseRuntimeOutputIndex_t = std::int32_t;
using PulseRuntimeVarIndex_t = std::int32_t;
using MeshDrawPrimitiveFlags_t = std::uint32_t;
using VertexAlbedoFormat_t = std::uint8_t;
using AnimParamID = std::uint32_t;
using AnimNodeID = std::uint32_t;
using ParticleModelType_t = std::uint32_t;
using PulseMethodCallMode_t = std::uint32_t;
using NmIKBlendMode_t = std::uint32_t;
using AnimValueSource = std::uint32_t;
using OrientationWarpMode_t = std::uint32_t;
using OrientationWarpTargetOffsetMode_t = std::uint32_t;
using OrientationWarpRootMotionSource_t = std::uint32_t;
using fieldtype_t = std::uint32_t;
using ParticleAttributeIndex_t = std::int32_t;
using ParticleIndex_t = std::int32_t;

// Cross-module types that are referenced across different DLLs
class SceneEventId_t {
public:
    std::uint32_t m_nSceneEventId;
};

class SndOpEventGuid_t {
public:
    std::uint64_t m_nGuid;
};

class CNetworkViewOffsetVector {
public:
    Vector m_vecOffset;
};

enum class HitGroup_t : std::int32_t {
    HITGROUP_INVALID = -1,
    HITGROUP_GENERIC = 0x0,
    HITGROUP_HEAD = 0x1,
    HITGROUP_CHEST = 0x2,
    HITGROUP_STOMACH = 0x3,
    HITGROUP_LEFTARM = 0x4,
    HITGROUP_RIGHTARM = 0x5,
    HITGROUP_LEFTLEG = 0x6,
    HITGROUP_RIGHTLEG = 0x7,
    HITGROUP_NECK = 0x8,
    HITGROUP_UNUSED = 0x9,
    HITGROUP_GEAR = 0xA,
    HITGROUP_SPECIAL = 0xB,
    HITGROUP_COUNT = 0xC,
};

enum class RenderMode_t : std::uint8_t {
    kRenderNormal = 0x0,
    kRenderTransAlpha = 0x1,
    kRenderNone = 0x2,
    kRenderModeCount = 0x3,
};

enum class RenderFx_t : std::uint8_t {
    kRenderFxNone = 0x0,
    kRenderFxPulseSlow = 0x1,
    kRenderFxPulseFast = 0x2,
    kRenderFxPulseSlowWide = 0x3,
    kRenderFxPulseFastWide = 0x4,
    kRenderFxFadeSlow = 0x5,
    kRenderFxFadeFast = 0x6,
    kRenderFxSolidSlow = 0x7,
    kRenderFxSolidFast = 0x8,
    kRenderFxStrobeSlow = 0x9,
    kRenderFxStrobeFast = 0xA,
    kRenderFxStrobeFaster = 0xB,
    kRenderFxFlickerSlow = 0xC,
    kRenderFxFlickerFast = 0xD,
    kRenderFxFadeOut = 0xE,
    kRenderFxFadeIn = 0xF,
    kRenderFxPulseFastWider = 0x10,
    kRenderFxMax = 0x11,
};

enum class DecalRtEncoding_t : std::uint8_t {
    DECAL_RT_ENCODING_NONE = 0x0,
    DECAL_RT_ENCODING_NORMAL = 0x1,
    DECAL_RT_ENCODING_EMISSIVE = 0x2,
};

// Additional cross-module enum types
enum class PointOrientGoalDirectionType_t : std::uint32_t {};
enum class PointOrientConstraint_t : std::uint32_t {};
enum class ValueRemapperInputType_t : std::uint32_t {};
enum class ValueRemapperOutputType_t : std::uint32_t {};
enum class ValueRemapperHapticsType_t : std::uint32_t {};
enum class ValueRemapperMomentumType_t : std::uint32_t {};
enum class ValueRemapperRatchetType_t : std::uint32_t {};
enum class PlayerConnectedState : std::uint32_t {};
enum class EntityDisolveType_t : std::uint32_t {};
enum class GrenadeType_t : std::uint32_t {};
enum class BeamType_t : std::uint32_t {};
enum class BeamClipStyle_t : std::uint32_t {};

// CBitVec template
template <int N>
class CBitVec {
public:
    std::uint32_t m_Data[(N + 31) / 32];
};

// Additional missing types
class CSoundPatch;
enum class C_BaseCombatCharacter_WaterWakeMode_t : std::uint32_t {};
enum class DamageTypes_t : std::uint32_t {};
enum class WeaponGameplayAnimState : std::uint32_t {};
enum class CSWeaponMode : std::uint32_t {};
enum class DoorState_t : std::uint32_t {};
enum class CSPlayerBlockingUseAction_t : std::uint32_t {};
class CParticleCollectionFloatInput;
class CPerParticleFloatInput;
class CParticleCollectionVecInput;
enum class ParticleColorBlendType_t : std::uint32_t {};
class CPerParticleVecInput;
class CParticleRemapFloatInput;
enum class ParticleSetMethod_t : std::uint32_t {};
class CParticleCollectionRendererFloatInput;
class CParticleCollectionRendererVecInput;
enum class ParticleNamedValueSource_t : std::uint32_t {};
enum class ParticleDirectionNoiseType_t : std::uint32_t {};
enum class AnimationType_t : std::uint32_t {};
enum class IChoreoServices_ScriptState_t : std::uint32_t {};
enum class IChoreoServices_ChoreoState_t : std::uint32_t {};
class CGenericShapeProxy;
template <int N> class CTypedBitVec;
using BASEPTR = void*;
using ENTITYFUNCPTR = void*;
using USEPTR = void*;
enum class ScriptedMoveTo_t : std::uint32_t {};
enum class SharedMovementGait_t : std::uint32_t {};
enum class ScriptedHeldWeaponBehavior_t : std::uint32_t {};
enum class ESceneViewDebugOverlaysListenerDataType_t : std::uint32_t {};
enum class soundlevel_t : std::uint32_t {};
class CVariantDefaultAllocator;
enum class CFuncMover_Move_t : std::uint32_t {};
enum class CFuncMover_OrientationUpdate_t : std::uint32_t {};
enum class CFuncMover_TransitionToPathNodeAction_t : std::uint32_t {};
enum class CFuncMover_FollowEntityDirection_t : std::uint32_t {};
enum class CFuncMover_FollowConstraint_t : std::uint32_t {};
enum class CFuncRotator_Rotate_t : std::uint32_t {};
class IPhysicsBody;
enum class CLogicBranchList_LogicBranchListenerLastState_t : std::uint32_t {};
enum class INavObstacle_NavObstacleType_t : std::uint32_t {};
class constraint_hingeparams_t;
enum class JointMotion_t : std::uint32_t {};
enum class DynamicContinuousContactBehavior_t : std::uint32_t {};
enum class CPhysicsProp_CrateType_t : std::uint32_t {};
class InfoForResourceTypeCVoiceContainerBase;
class InfoForResourceTypeCVMixListResource;
template<typename T> class CSteamAudioMovableBakedData;
class IPLCompressedEnergyFields;
class IPLProbeBatch;
class IPLScene;
class IPLStaticMesh;
class FourVectors;
class FourQuaternions;
template<typename T> class SphereBase_t;
class CUtlVectorSIMDPaddedVector;
enum class ParticleColorBlendMode_t : std::uint32_t {};
class CParticleTransformInput;
class CParticleVariableRef;
class CParticleModelInput;

// Forward declarations for classes and types
class CAnimGraphControllerManager;
class CAnimGraphControllerBase;
class IPhysicsRagdollControl;
class SceneRequestHandle_t;
class SceneOpportunityHandle_t;
class CCSPlayerAnimationState;
using HSCRIPT = void*;

enum class PointTemplateClientOnlyEntityBehavior_t : std::uint32_t {};
enum class PointTemplateOwnerSpawnGroupType_t : std::uint32_t {};
enum class QuestProgress_Reason : std::uint32_t {};
enum class PointWorldTextJustifyHorizontal_t : std::uint32_t {};
enum class PointWorldTextJustifyVertical_t : std::uint32_t {};
enum class PointWorldTextReorientMode_t : std::uint32_t {};

// Animation and transform types
class CMotionTransform {
public:
    Vector m_vPosition;
    Quaternion m_qOrientation;
    float m_flScale;
};

class RenderInputLayoutField_t {
public:
    std::uint8_t m_Data[32]; // Placeholder
};

class CAnimVariant {
public:
    std::uint8_t m_Data[32]; // Placeholder
};

class CGlobalSymbolCaseSensitive {
public:
    std::uint64_t m_Id;
};

// Resource info types for texture and animation data
class InfoForResourceTypeCTextureBase {
public:
    std::uint8_t m_Data[8]; // Placeholder - resource handle
};

class InfoForResourceTypeCAnimData {
public:
    std::uint8_t m_Data[8]; // Placeholder - resource handle
};

// Physics types
class RnSphereDesc_t {
public:
    std::uint8_t m_Data[32]; // Placeholder
};

class RnCapsuleDesc_t {
public:
    std::uint8_t m_Data[32]; // Placeholder
};

class RnHullDesc_t {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

class RnMeshDesc_t {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

class RnSoftbodyParticle_t {
public:
    std::uint8_t m_Data[32]; // Placeholder
};

class RnSoftbodySpring_t {
public:
    std::uint8_t m_Data[16]; // Placeholder
};

class RnSoftbodyCapsule_t {
public:
    std::uint8_t m_Data[32]; // Placeholder
};

// Additional forward declarations for nested types
class CNmVectorInfoNode_Info_t {
public:
    std::uint8_t m_Data[4]; // Placeholder
};

class CNmFloatAngleMathNode_Operation_t {
public:
    std::uint8_t m_Data[4]; // Placeholder
};

class CNmFloatMathNode_Operator_t {
public:
    std::uint8_t m_Data[4]; // Placeholder
};

class CNmTargetInfoNode_Info_t {
public:
    std::uint8_t m_Data[4]; // Placeholder
};

class CSplitScreenSlot {
public:
    std::uint8_t m_Data[8]; // Placeholder
};

class CUtlStringToken {
public:
    std::uint32_t m_nHashCode;
};

class CResourceName {
public:
    std::uint64_t m_nHashCode;
};

class CNmTimeConditionNode_ComparisonType_t {
public:
    std::uint8_t m_Data[4]; // Placeholder
};

class CNmTimeConditionNode_Operator_t {
public:
    std::uint8_t m_Data[4]; // Placeholder
};

class CNmSyncEventIndexConditionNode_TriggerMode_t {
public:
    std::uint8_t m_Data[4]; // Placeholder
};

class CModelAnimNameWithDeltas {
public:
    std::uint8_t m_Data[32]; // Placeholder
};

class CNmParticleEvent_Type_t {
public:
    std::uint8_t m_Data[4]; // Placeholder
};

class CNmStateNode_TimedEvent_t_Comparison_t {
public:
    std::uint8_t m_Data[4]; // Placeholder
};

class CKV3MemberNameWithStorage {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

class CRotation {
public:
    std::uint8_t m_Data[4]; // Placeholder - likely a quaternion or rotation representation
};

class InfoForResourceTypeCPhysAggregateData {
public:
    std::uint8_t m_Data[8]; // Placeholder - resource handle
};

class InfoForResourceTypeCAnimationGroup {
public:
    std::uint8_t m_Data[8]; // Placeholder - resource handle
};

class InfoForResourceTypeCSequenceGroupData {
public:
    std::uint8_t m_Data[8]; // Placeholder - resource handle
};

class CRangeFloat {
public:
    float m_flMin;
    float m_flMax;
};

class Range_t {
public:
    float m_flMin;
    float m_flMax;
};

struct PackedAABB_t {
    std::uint32_t m_nPackedMin;
    std::uint32_t m_nPackedMax;
};

// Entity index type - used for entity identification
struct CEntityIndex {
    std::int32_t m_Value;
};

// Physics types - forward declarations
struct PhysFeModelDesc_t {
    std::uint8_t m_Data[128]; // Placeholder
};

// Rendering types
enum class RenderPrimitiveType_t : std::uint32_t {
    RENDER_PRIM_TRIANGLES = 0,
    RENDER_PRIM_POINTS = 1,
    RENDER_PRIM_LINES = 2,
    RENDER_PRIM_TRIANGLE_STRIP = 3,
};

// KeyValues3 member name set
class CKV3MemberNameSet {
public:
    std::uint8_t m_Data[32]; // Placeholder
};

// Particle system interface
class IParticleCollection {
public:
    virtual ~IParticleCollection() = default;
    std::uint8_t m_Data[128]; // Placeholder
};

// Compression template class - used for data compression in animation system
template <typename T>
class CCompressor {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

// Nested enum/class types that appear in schema - these are typically enums or small structs
// They are referenced with :: in the schema but sanitized to _ in the generated code
using CNmSoundEvent_Position_t = std::uint8_t;
using CNmRootMotionData_SamplingMode_t = std::uint8_t;
using CNmFloatComparisonNode_Comparison_t = std::uint8_t;
using CNmIDComparisonNode_Comparison_t = std::uint8_t;
using CNmTargetWarpNode_TargetUpdateRule_t = std::uint8_t;
using CNmFloatAngleMathNode_Operator_t = std::uint8_t;
using CNmFloatMathNode_Operation_t = std::uint8_t;
using CNmTimeConditionNode_Comparison_t = std::uint8_t;
using CNmSyncEventIndexConditionNode_Comparison_t = std::uint8_t;
using CNmStateNode_Comparison_t = std::uint8_t;
using CNmCurrentSyncEventNode_Mode_t = std::uint8_t;
using CNmCurrentSyncEventNode_InfoType_t = std::uint8_t;
using CNmVectorInfoNode_Component_t = std::uint8_t;
using CNmTargetInfoNode_Info_e = std::uint32_t;
using CNmParticleEvent_Mode_t = std::uint32_t;
using CNmTransitionNode_Flags_t = std::uint8_t;
using CNmEventTargetEntity_t = std::uint32_t;
using CNmRootMotionOverrideNode_Flags_t = std::uint8_t;
using MedalRank_t = std::uint32_t;

// Base component classes - these are base classes for player/controller components
class CPlayerPawnComponent {
public:
    std::uint8_t m_Data[8]; // Placeholder
};

class CPlayerControllerComponent {
public:
    std::uint8_t m_Data[8]; // Placeholder
};

// Entity IO output type - used for entity input/output system
class CEntityIOOutput {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

// Entity output template - used for typed entity outputs
template <typename T>
class CEntityOutputTemplate {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

// Point camera settings - used for camera configuration
struct PointCameraSettings_t {
    std::uint8_t m_Data[64]; // Placeholder
};

// Light effect type - used for light effects
struct C4LightEffect_t {
    std::uint8_t m_Data[32]; // Placeholder
};

// Player state type - used for player state tracking
struct CSPlayerState {
    std::uint8_t m_Data[32]; // Placeholder
};

// Performance mode type - used for performance settings
using PerformanceMode_t = std::uint32_t;

// Breakable contents type - used for breakable props
using BreakableContentsType_t = std::uint32_t;

// Particle attachment type - used for particle system attachments
using ParticleAttachment_t = std::uint32_t;

// Precipitation filter type - used for weather effects
using PrecipitationFilter_t = std::uint32_t;

// Observer interpolation state - used for spectator camera
using ObserverInterpState_t = std::uint32_t;

// Sequence handle type - used for animation sequences
using HSequence = std::uint32_t;

// Animation loop mode type - used for animation playback
using AnimLoopMode_t = std::uint32_t;

// Button state type - used for input button tracking
class CInButtonState {
public:
    std::uint64_t m_pnButtons[3];
};

// Animation algorithm type - used for animation system
using AnimationAlgorithm_t = std::uint32_t;

// External animation graph handle - used for animation graphs
using ExternalAnimGraphHandle_t = std::uint32_t;

// Networked quantized float - used for network compression
class CNetworkedQuantizedFloat {
public:
    float m_flValue;
};

// Sequence finish notify state - used for animation sequence notifications
using SequenceFinishNotifyState_t = std::uint32_t;

// Resource ID type - used for resource identification
using ResourceId_t = std::uint64_t;

// Skeleton animation controller - base class for animation controllers
class CSkeletonAnimationController {
public:
    std::uint8_t m_Data[128]; // Placeholder
};

// Animation graph instance - used for animation graph instances
class CNmGraphInstance {
public:
    std::uint8_t m_Data[256]; // Placeholder
};

// External animation graph struct - used for external animation graphs
struct ExternalAnimGraph_t {
    std::uint8_t m_Data[64]; // Placeholder
};

// Physics motion controller interface - used for physics simulation
class IPhysicsMotionController {
public:
    virtual ~IPhysicsMotionController() = default;
    std::uint8_t m_Data[64]; // Placeholder
};

// Filter type - used for entity filtering
struct filter_t {
    std::uint8_t m_Data[32]; // Placeholder
};

// Soundevent path corner pair - used for sound events
struct SoundeventPathCornerPairNetworked_t {
    std::uint8_t m_Data[32]; // Placeholder
};

// Model config handle - used for model configuration
using ModelConfigHandle_t = std::uint32_t;

// Solid type - used for collision detection
using SolidType_t = std::uint8_t;

// Surrounding bounds type - used for bounding box calculations
using SurroundingBoundsType_t = std::uint8_t;

// Shard solid type - used for breakable glass/props
enum class ShardSolid_t : std::uint8_t {
    SHARD_SOLID = 0x0,
    SHARD_DEBRIS = 0x1,
};

// Fix angle set type - used for view angle changes
enum class FixAngleSet_t : std::uint8_t {
    None = 0x0,
    Absolute = 0x1,
    Relative = 0x2,
};

// Animation graph parameter optional reference template - used for animation graph parameters
template <typename T>
class CAnimGraph2ParamOptionalRef {
public:
    std::uint8_t m_Data[24]; // Placeholder
};

// Animation graph parameter auto-reset optional reference - used for animation graph parameters
class CAnimGraph2ParamAutoResetOptionalRef {
public:
    std::uint8_t m_Data[24]; // Placeholder
};

// Additional enum types used in weapon and entity systems
using attributeprovidertypes_t = std::uint32_t;
using ENPCBehaviorOverride_t = std::uint32_t;
using InteractionPriority_t = std::uint32_t;
using CSWeaponType = std::uint32_t;
using CSWeaponCategory = std::uint32_t;
using gear_slot_t = std::uint32_t;
using loadout_slot_t = std::uint32_t;
using CSWeaponSilencerType = std::uint32_t;

// Firing mode float - used for weapon firing modes
class CFiringModeFloat {
public:
    float m_flValues[2];
};

// Firing mode int - used for weapon firing modes
class CFiringModeInt {
public:
    std::int32_t m_nValues[2];
};

// Skill float - used for difficulty scaling
class CSkillFloat {
public:
    float m_flValue;
};

// Transform world space - used for entity transforms
class CTransformWS {
public:
    Vector m_vPosition;
    Quaternion m_qOrientation;
};

// Network origin cell coord quantized vector - used for networked positions
class CNetworkOriginCellCoordQuantizedVector {
public:
    std::uint16_t m_cellX;
    std::uint16_t m_cellY;
    std::uint16_t m_cellZ;
    std::uint16_t m_nOutsideWorld;
    Vector m_vecX;
    Vector m_vecY;
    Vector m_vecZ;
};

// Entity handle - used for entity references
class CEntityHandle {
public:
    std::uint32_t m_Index;
};

// Player slot - used for player identification
class CPlayerSlot {
public:
    std::int32_t m_Value;
};

// Physics aggregate instance interface - used for physics
class IPhysAggregateInstance {
public:
    virtual ~IPhysAggregateInstance() = default;
    std::uint8_t m_Data[64]; // Placeholder
};

// Observer mode - used for spectator camera modes
enum class ObserverMode_t : std::uint32_t {
    OBS_MODE_NONE = 0,
    OBS_MODE_FIXED = 1,
    OBS_MODE_IN_EYE = 2,
    OBS_MODE_CHASE = 3,
    OBS_MODE_ROAMING = 4,
};

// Sound event name - used for sound system
class CSoundEventName {
public:
    std::uint8_t m_Data[32]; // Placeholder
};

// Attachment handle - used for model attachments
using AttachmentHandle_t = std::uint16_t;

// Timeline compression - used for animation timeline compression
enum class TimelineCompression_t : std::uint32_t {
    TIMELINE_COMPRESSION_SUM = 0,
    TIMELINE_COMPRESSION_COUNT_PER_INTERVAL = 1,
    TIMELINE_COMPRESSION_AVERAGE = 2,
    TIMELINE_COMPRESSION_AVERAGE_BLEND = 3,
    TIMELINE_COMPRESSION_TOTAL = 4,
};

// Kill types - used for kill tracking
enum class EKillTypes_t : std::uint32_t {
    KILL_NONE = 0,
    KILL_DEFAULT = 1,
    KILL_HEADSHOT = 2,
    KILL_BLAST = 3,
    KILL_BURN = 4,
    KILL_SLASH = 5,
};

// Weapon sound - used for weapon sound events
enum class WeaponSound_t : std::uint32_t {
    WEAPON_SOUND_EMPTY = 0,
    WEAPON_SOUND_SINGLE_SHOT = 1,
    WEAPON_SOUND_SINGLE_SHOT_NPC = 2,
    WEAPON_SOUND_DOUBLE_SHOT = 3,
    WEAPON_SOUND_DOUBLE_SHOT_NPC = 4,
    WEAPON_SOUND_BURST = 5,
    WEAPON_SOUND_RELOAD = 6,
    WEAPON_SOUND_RELOAD_NPC = 7,
    WEAPON_SOUND_MELEE_MISS = 8,
    WEAPON_SOUND_MELEE_HIT = 9,
    WEAPON_SOUND_MELEE_HIT_WORLD = 10,
    WEAPON_SOUND_SPECIAL1 = 11,
    WEAPON_SOUND_SPECIAL2 = 12,
    WEAPON_SOUND_SPECIAL3 = 13,
    WEAPON_SOUND_TAUNT = 14,
    WEAPON_SOUND_DEPLOY = 15,
};

// Attachment name symbol with storage - used for model attachments
class CAttachmentNameSymbolWithStorage {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

// Item flag types - used for item flags
enum class ItemFlagTypes_t : std::uint32_t {
    ITEM_FLAG_NONE = 0,
    ITEM_FLAG_CAN_SELECT_WITH_USE = 1,
    ITEM_FLAG_NOAUTORELOAD = 2,
    ITEM_FLAG_NOAUTOSWITCHEMPTY = 4,
    ITEM_FLAG_LIMITINWORLD = 8,
    ITEM_FLAG_EXHAUSTIBLE = 16,
    ITEM_FLAG_DOHITLOCATIONDMG = 32,
    ITEM_FLAG_NOAMMOPICKUPS = 64,
    ITEM_FLAG_NOITEMPICKUP = 128,
};

// Ammo index - used for ammunition types
using AmmoIndex_t = std::int32_t;

// Rumble effect - used for controller rumble
enum class RumbleEffect_t : std::uint32_t {
    RUMBLE_INVALID = 0xFFFFFFFF,
    RUMBLE_STOP_ALL = 0,
    RUMBLE_PISTOL = 1,
    RUMBLE_357 = 2,
    RUMBLE_SMG1 = 3,
    RUMBLE_AR2 = 4,
    RUMBLE_SHOTGUN_SINGLE = 5,
    RUMBLE_SHOTGUN_DOUBLE = 6,
    RUMBLE_AR2_ALT_FIRE = 7,
    RUMBLE_RPG_MISSILE = 8,
    RUMBLE_CROWBAR_SWING = 9,
    RUMBLE_AIRBOAT_GUN = 10,
    RUMBLE_JEEP_ENGINE_LOOP = 11,
    RUMBLE_FLAT_LEFT = 12,
    RUMBLE_FLAT_RIGHT = 13,
    RUMBLE_FLAT_BOTH = 14,
    RUMBLE_DMG_LOW = 15,
    RUMBLE_DMG_MED = 16,
    RUMBLE_DMG_HIGH = 17,
    RUMBLE_FALL_LONG = 18,
    RUMBLE_FALL_SHORT = 19,
    RUMBLE_PHYSCANNON_OPEN = 20,
    RUMBLE_PHYSCANNON_PUNT = 21,
    RUMBLE_PHYSCANNON_LOW = 22,
    RUMBLE_PHYSCANNON_MEDIUM = 23,
    RUMBLE_PHYSCANNON_HIGH = 24,
};

// ============================================================================
// SDK Helper Functions and Macros
// ============================================================================

namespace sdk {

    // Helper to determine the const-qualified return type
    // For non-pointer types: const T&
    // For pointer types: T* const& (const pointer, not pointer-to-const)
    template <typename T>
    struct const_field_type {
        using type = const T&;
    };

    template <typename T>
    struct const_field_type<T*> {
        using type = T* const&;
    };

    // Convert `this + offset` to a typed reference. Zero-overhead in
    // release builds; produces an lvalue you can read or assign to.
    template <typename T>
    inline T& field_ref(void* base, std::ptrdiff_t off) noexcept {
        return *reinterpret_cast<T*>(reinterpret_cast<std::byte*>(base) + off);
    }

    template <typename T>
    inline typename const_field_type<T>::type field_ref(const void* base, std::ptrdiff_t off) noexcept {
        return *reinterpret_cast<T*>(const_cast<std::byte*>(reinterpret_cast<const std::byte*>(base)) + off);
    }

} // namespace sdk

// SCHEMA_FIELD(type, name, offset)
//
// Expands to a pair of inline accessors:
//
//     T&       name()       { return sdk::field_ref<T>(this, off); }
//     const T& name() const { return sdk::field_ref<T>(this, off); }
//
// For pointer types, the const version returns T* const& (const pointer, not pointer to const)
// Use it as: `pawn->m_iHealth() = 100;`
#define SCHEMA_FIELD(TYPE, NAME, OFFSET)                                           \
    inline TYPE&       NAME()       noexcept { return ::sdk::field_ref<TYPE>(this, (OFFSET)); } \
    inline auto        NAME() const noexcept -> decltype(::sdk::field_ref<TYPE>(this, (OFFSET))) { return ::sdk::field_ref<TYPE>(this, (OFFSET)); }

// SCHEMA_PAD(name, size) — anonymous padding when you want to
// pre-declare a struct layout exactly. Optional.
#define SCHEMA_PAD(NAME, SIZE) std::byte NAME[(SIZE)]

// ============================================================================
// Cross-module forward declarations (auto-generated)
// These provide declaration-only stubs for types referenced across
// different sdk::<module> namespaces so headers can be included in any
// order. They are intentionally declaration-only; the real definitions
// live in the per-module headers.

namespace animationsystem {
    enum class AnimationType_t : std::uint32_t;
    class AttachmentHandle_t;
    class CNmTarget;
    class CParticleCollectionFloatInput;
    class CParticleCollectionRendererFloatInput;
    class CParticleCollectionRendererVecInput;
    class CParticleCollectionVecInput;
    class CParticleModelInput;
    class CParticleProperty;
    class CParticleRemapFloatInput;
    class CParticleTransformInput;
    class CParticleVariableRef;
    class CPerParticleFloatInput;
    class CPerParticleVecInput;
    class CPulse_OutflowConnection;
    class CPulse_ResumePoint;
    class HSequence;
    enum class MeshDrawPrimitiveFlags_t : std::uint32_t;
    enum class ParticleAttachment_t : std::int32_t;
    class PulseCursorID_t;
    class PulseNodeDynamicOutflows_t;
    class PulseSelectorOutflowList_t;
    enum class ScriptedHeldWeaponBehavior_t : std::int32_t;
    enum class ScriptedMoveTo_t : std::uint32_t;
    enum class SharedMovementGait_t : std::int8_t;
    class SignatureOutflow_Continue;
    class SignatureOutflow_Resume;
    enum class VertexAlbedoFormat_t : std::uint8_t;
}

namespace client {
    class CAttributeList;
    class CAttributeManager_cached_attribute_float_t;
    class CBasePlayerController;
    class CBodyComponent;
    class CBuoyancyHelper;
    class CCSGameModeRules;
    class CCSMinimapVolume;
    class CCSPlayerController;
    class CCSPlayer_ActionTrackingServices;
    class CCSPlayer_AimPunchServices;
    class CCSPlayer_BulletServices;
    class CCSPlayer_BuyServices;
    class CCSPlayer_DamageReactServices;
    class CCSPlayer_HostageServices;
    class CCSPlayer_PingServices;
    class CChoreoComponent;
    class CCollisionProperty;
    class CDestructiblePartsComponent;
    class CEnvSoundscapeTriggerable;
    class CGlowProperty;
    class CHitboxComponent;
    class CLightComponent;
    class CPathMover;
    class CPathSimple;
    class CPathWithDynamicNodes;
    class CPlayer_AutoaimServices;
    class CPlayer_CameraServices;
    class CPlayer_FlashlightServices;
    class CPlayer_ItemServices;
    class CPlayer_MovementServices;
    class CPlayer_ObserverServices;
    class CPlayer_UseServices;
    class CPlayer_WaterServices;
    class CPlayer_WeaponServices;
    class CPropDataComponent;
    class CRenderComponent;
    class CSkeletonInstance;
    class CountdownTimer;
    class EntityRenderAttribute_t;
    class EntitySpottedState_t;
    class IntervalTimer;
    class PhysicsRagdollPose_t;
    class ViewAngleServerChange_t;
    class fogparams_t;
    class shard_model_desc_t;
    class sky3dparams_t;
}

namespace engine2 {
    class CEntityAttributeTable;
    class CEntityIOOutput;
    class CEntityKeyValues;
    class CNetworkVarChainer;
    class CVariantDefaultAllocator;
    class GameTime_t;
}

namespace particles {
    class ParticleAttributeIndex_t;
    class ParticleIndex_t;
    class ParticleModelType_t;
}

namespace rendersystemdx11 {
    class RenderInputLayoutField_t;
    class RenderPrimitiveType_t;
}

namespace resourcesystem {
    class FourQuaternions;
    class NoiseStreamDef_t;
}

namespace scenesystem {
    enum class DecalRtEncoding_t : std::uint8_t;
    enum class ESceneViewDebugOverlaysListenerDataType_t : std::uint32_t;
}

namespace schemasystem {
    class ResourceId_t;
}

namespace server {
    class AmmoIndex_t;
    enum class AnimLoopMode_t : std::int32_t;
    enum class AnimationAlgorithm_t : std::int8_t;
    enum class BeamType_t : std::uint32_t;
    enum class BloodType : std::int32_t;
    enum class BreakableContentsType_t : std::uint32_t;
    enum class C4LightEffect_t : std::uint32_t;
    class CAnimGraph2InstancePtr;
    class CAnimGraphControllerPtr;
    class CAttributeManager;
    class CBaseAnimGraph;
    class CBaseFilter;
    class CBaseProp;
    class CCSPlayerAnimationState;
    class CEntityComponent;
    class CExternalAnimGraphList;
    class CFiringModeFloat;
    class CFiringModeInt;
    class CInButtonState;
    class CNetworkOriginCellCoordQuantizedVector;
    class CNetworkTransmitComponent;
    class CNetworkVelocityVector;
    class CNetworkViewOffsetVector;
    class CPathNode;
    enum class CSPlayerBlockingUseAction_t : std::uint32_t;
    enum class CSPlayerState : std::uint32_t;
    enum class CSWeaponCategory : std::uint32_t;
    enum class CSWeaponMode : std::uint32_t;
    enum class CSWeaponSilencerType : std::uint32_t;
    enum class CSWeaponType : std::uint32_t;
    class CSkillFloat;
    class CSoundPatch;
    enum class CustomCameraMode_t : std::uint8_t;
    enum class DamageTypes_t : std::uint32_t;
    enum class DirectionAlongSimplePath_t : std::uint32_t;
    enum class DoorState_t : std::uint32_t;
    enum class EKillTypes_t : std::uint8_t;
    enum class EntityDissolveType_t : std::int32_t;
    enum class EntityPlatformTypes_t : std::uint8_t;
    class ExternalAnimGraphHandle_t;
    enum class FixAngleSet_t : std::uint8_t;
    enum class GrenadeType_t : std::uint32_t;
    class HUDPanelDialogVariableString_t;
    class HUDPanelHasClass_t;
    enum class HitGroup_t : std::int32_t;
    enum class ItemFlagTypes_t : std::uint8_t;
    enum class MedalRank_t : std::uint32_t;
    class ModelConfigHandle_t;
    enum class MoveCollide_t : std::uint8_t;
    enum class MoveType_t : std::uint8_t;
    enum class ObserverInterpState_t : std::uint32_t;
    enum class ObserverMode_t : std::uint32_t;
    enum class PerformanceMode_t : std::uint32_t;
    enum class PlayerConnectedState : std::int32_t;
    class PointCameraSettings_t;
    enum class PointOrientConstraint_t : std::uint32_t;
    enum class PointOrientGoalDirectionType_t : std::uint32_t;
    enum class PointTemplateClientOnlyEntityBehavior_t : std::uint32_t;
    enum class PointTemplateOwnerSpawnGroupType_t : std::uint32_t;
    enum class PointWorldTextJustifyHorizontal_t : std::uint32_t;
    enum class PointWorldTextJustifyVertical_t : std::uint32_t;
    enum class PointWorldTextReorientMode_t : std::uint32_t;
    class PrecipitationFilter_t;
    class QuestProgress_Reason;
    enum class RenderFx_t : std::uint8_t;
    enum class RenderMode_t : std::uint8_t;
    enum class RumbleEffect_t : std::int32_t;
    class SceneEventId_t;
    enum class SequenceFinishNotifyState_t : std::uint8_t;
    enum class ShardSolid_t : std::uint8_t;
    enum class SolidType_t : std::uint8_t;
    class SoundeventBoxHelperNetworked_t;
    class SoundeventPathCornerPairNetworked_t;
    enum class SurroundingBoundsType_t : std::uint8_t;
    enum class TakeDamageFlags_t : std::uint64_t;
    enum class TimelineCompression_t : std::uint32_t;
    enum class ValueRemapperHapticsType_t : std::uint32_t;
    enum class ValueRemapperInputType_t : std::uint32_t;
    enum class ValueRemapperMomentumType_t : std::uint32_t;
    enum class ValueRemapperOutputType_t : std::uint32_t;
    enum class ValueRemapperRatchetType_t : std::uint32_t;
    enum class WeaponGameplayAnimState : std::uint16_t;
    enum class WeaponSound_t : std::uint32_t;
    enum class filter_t : std::uint32_t;
    enum class gear_slot_t : std::int32_t;
    enum class loadout_slot_t : std::int32_t;
    class thinkfunc_t;
}

namespace soundsystem {
    enum class soundlevel_t : std::uint32_t;
}

namespace vphysics2 {
    class CGenericShapeProxy;
    enum class DynamicContinuousContactBehavior_t : std::uint8_t;
    class IPhysAggregateInstance;
    class IPhysicsBody;
    class IPhysicsJoint;
    class IPhysicsMotionController;
    class IPhysicsRagdollControl;
    enum class JointMotion_t : std::uint32_t;
    class PhysFeModelDesc_t;
    enum class PhysInterfaceId_t : std::uint32_t;
    class RnCompoundDesc_t;
    class constraint_hingeparams_t;
}

// Auto-generated: forward declarations for types the runtime schemas
// reference but that aren't defined in any included header.
template <class...> class CPulseObservableExpression;
template <class...> class CUtlDict;
template <class...> class HPulseCell;
class CFuncMover_FindFollowMoverStrategy_t;
class CFuncMover_PathRebuildStrategy_t;
class CFuncRotator_RotationAxis_t;
class CGameSoundEventName;
class CNmClothEvent_Type_t;
class CNmOrientationWarpNode_AlignmentMode_t;
class CPathMoverEntitySpawner_TemplateChoiceStrategy_t;
class CPulseArgumentPack;
class CPulseInputParamMap;
class CPulseVariant;
class HPulseCellBase;
class HYieldedCursor;
class RnSphere_t;

