// Generated by cs2-sdk — https://cs2-sdk.com
//
// module:        vphysics2.dll
// classes:       117
// enums:         5
// generated_at:  2026-09-24T11:13:20.869142400+00:00
//
// Use:
//   auto* pawn = reinterpret_cast<C_CSPlayerPawn*>(addr);
//   pawn->m_iHealth() = 100;

#pragma once
#include "../macros.hpp"

namespace vphysics2 {

    class RnSphereDesc_t;
    class RnCompoundDesc_t;
    class RnSoftbodyParticle_t;
    class RnHullDesc_t;
    class RnCapsuleDesc_t;
    class PhysFeModelDesc_t;
    class RnMeshDesc_t;
    class RnSoftbodySpring_t;
    class RnSoftbodyCapsule_t;
    class vphysics_save_cphysicsbody_t;
    class FeBuildBoxRigid_t;
    class CFeIndexedJiggleBone;
    class FeBoneMergeLink_t;
    class IPhysAggregateInstance;
    class FeBandBendLimit_t;
    class RnCompoundTree_t;
    class FeTaperedCapsuleStretch_t;
    class constraint_axislimit_t;
    class FeSimdRodConstraintAnim_t;
    class FeSimdRodConstraint_t;
    class IPhysicsParticleRope;
    class constraint_hingeparams_t;
    class IPhysicsBodyList;
    class FeBuildSphereRigid_t;
    class FeSimdAnimStrayRadius_t;
    class RnTriangle_t;
    class FeProxyVertexMap_t;
    class FeNodeIntegrator_t;
    class RnCapsule_t;
    class CFeNamedJiggleBone;
    class FePrism_t;
    class FeAntiTunnelProbeBuild_t;
    class RnBodyDesc_t;
    class OldFeEdge_t;
    class FeFollowNode_t;
    class RnMesh_t;
    class VertexPositionNormal_t;
    class IPhysicsRagdollControl;
    class RnCompoundTreeNode_t;
    class FeBuildSDFRigid_t;
    class RnBlendVertex_t;
    class CFeMorphLayer;
    class FeCtrlSoftOffset_t;
    class VPhysEntityId_t;
    class RnCompound_t;
    class FeVertexMapDesc_t;
    class FeTaperedCapsuleRigid_t;
    class FeAnimStrayRadius_t;
    class IPhysicsJoint;
    class FeEdgeDesc_t;
    class FeNodeStrayBox_t;
    class FeNodeReverseOffset_t;
    class RnPlane_t;
    class FeSDFRigid_t;
    class CFeJiggleBone;
    class CRegionSVM;
    class FeWorldCollisionParams_t;
    class CGenericShapeProxy;
    class RnNode_t;
    class FeFitMatrix_t;
    class FeSimdQuad_t;
    class FeSimdSpringIntegrator_t;
    class FeSimdNodeBase_t;
    class FeQuad_t;
    class FeHingeLimit_t;
    class RnWing_t;
    class FeWeightedNode_t;
    class CollisionDetailLayerInfo_t;
    class FeEffectDesc_t;
    class FeSpringIntegrator_t;
    class FourVectors2D;
    class FeKelagerBend2_t;
    class vphysics_save_ragdoll_control_t;
    class FeRigidColliderIndices_t;
    class FeCollisionPlane_t;
    class FeStiffHingeBuild_t;
    class FeBoxRigid_t;
    class FeMorphLayerDepr_t;
    class FeCtrlOffset_t;
    class IPhysicsPlayerController;
    class FeNodeBase_t;
    class FeVertexMapBuild_t;
    class CFeVertexMapBuildArray;
    class FeTri_t;
    class RnHull_t;
    class FeModelSelfCollisionLayer_t;
    class FeAntiTunnelGroupBuild_t;
    class CovMatrix3;
    class PhysicsParticleId_t;
    class RnVertex_t;
    class IPhysicsMotionController;
    class Dop26_t;
    class FeDynKinLink_t;
    class RnFace_t;
    class FeSimdPrism_t;
    class FeCtrlOsOffset_t;
    class FeAntiTunnelProbe_t;
    class FeSourceEdge_t;
    class FeTwistConstraint_t;
    class FeNodeWindBase_t;
    class FeAxialEdgeBend_t;
    class FourCovMatrices3;
    class constraint_breakableparams_t;
    class FeSphereRigid_t;
    class CollisionDetailLayerInfo_t_Name_t;
    class FeBuildTaperedCapsuleRigid_t;
    class IPhysicsBody;
    class FeSoftParent_t;
    class RnShapeDesc_t;
    class FeTreeChildren_t;
    class FeRodConstraint_t;
    class FeFitWeight_t;
    class RnHalfEdge_t;
    class FeSimdTri_t;
    class VertexPositionColor_t;
    class FeFitInfluence_t;
    class FeHingeLimitBuild_t;

    enum class JointMotion_t : std::uint32_t {
        JOINT_MOTION_FREE = 0x0,
        JOINT_MOTION_LOCKED = 0x1,
        JOINT_MOTION_COUNT = 0x2,
    };

    enum class JointAxis_t : std::uint32_t {
        JOINT_AXIS_X = 0x0,
        JOINT_AXIS_Y = 0x1,
        JOINT_AXIS_Z = 0x2,
        JOINT_AXIS_COUNT = 0x3,
    };

    enum class DynamicContinuousContactBehavior_t : std::uint8_t {
        DYNAMIC_CONTINUOUS_ALLOW_IF_REQUESTED_BY_OTHER_BODY = 0x0,
        DYNAMIC_CONTINUOUS_ALWAYS = 0x1,
        DYNAMIC_CONTINUOUS_NEVER = 0x2,
    };

    enum class PhysInterfaceId_t : std::uint32_t {
        PIID_UNKNOWN = 0x0,
        PIID_IPHYSICSBODY = 0x1,
        PIID_IPHYSAGGREGATE = 0x2,
        PIID_IPHYSICSJOINT = 0x3,
        PIID_IPHYSICSMOTIONCONTROLLER = 0x4,
        PIID_IPHYSICSPARTICLEROPE = 0x5,
        PIID_IPHYSICSRAGDOLLCONTROL = 0x6,
        PIID_NUM_TYPES = 0x7,
    };

    enum class PhysGenericShapeType_t : std::uint8_t {
        GENERIC_SHAPE_POINT = 0x0,
        GENERIC_SHAPE_SPHERE = 0x1,
        GENERIC_SHAPE_AABB = 0x2,
        GENERIC_SHAPE_CAPSULE = 0x3,
        GENERIC_SHAPE_HULL = 0x4,
    };

    // CollisionDetailLayerInfo_t::Name_t
    //   fields: 2
    //   size: 0x10
    //   @MGetKV3ClassDefaults
    class CollisionDetailLayerInfo_t_Name_t {
    public:
        SCHEMA_FIELD(CUtlStringToken                 , m_nNameToken                                    , 0x0) // CUtlStringToken
        SCHEMA_FIELD(::CUtlString                    , m_sNameString                                   , 0x8) // CUtlString
    };

    // RnHullDesc_t
    //   fields: 1
    //   size: 0x110
    //   @MGetKV3ClassDefaults
    class RnHullDesc_t {
    public:
        SCHEMA_FIELD(RnHull_t                        , m_Hull                                          , 0x18) // RnHull_t
    };

    // RnTriangle_t
    //   fields: 1
    //   size: 0xC
    //   @MGetKV3ClassDefaults
    class RnTriangle_t {
    public:
        SCHEMA_FIELD(std::int32_t                    , m_nIndex                                        , 0x0) // int32[3]
    };

    // RnHull_t
    //   fields: 15
    //   size: 0xF8
    //   @MGetKV3ClassDefaults
    class RnHull_t {
    public:
        SCHEMA_FIELD(::Vector                        , m_vCentroid                                     , 0x0) // Vector
        SCHEMA_FIELD(float                           , m_flMaxAngularRadius                            , 0xC) // float32
        SCHEMA_FIELD(float                           , m_flMinCentroidRadius                           , 0x10) // float32
        SCHEMA_FIELD(::AABB_t                        , m_Bounds                                        , 0x14) // AABB_t
        SCHEMA_FIELD(::Vector                        , m_vOrthographicAreas                            , 0x2C) // Vector
        SCHEMA_FIELD(::matrix3x4_t                   , m_MassProperties                                , 0x38) // matrix3x4_t
        SCHEMA_FIELD(float                           , m_flVolume                                      , 0x68) // float32
        SCHEMA_FIELD(float                           , m_flSurfaceArea                                 , 0x6C) // float32
        SCHEMA_FIELD(CUtlVector<Vector>              , m_VertexPositions                               , 0x70) // CUtlVector<Vector>
        SCHEMA_FIELD(CUtlVector<RnPlane_t>           , m_FacePlanes                                    , 0x88) // CUtlVector<RnPlane_t>
        SCHEMA_FIELD(std::uint32_t                   , m_nFlags                                        , 0xA0) // uint32
        SCHEMA_FIELD(CRegionSVM*                     , m_pRegionSVM                                    , 0xA8) // CRegionSVM*
        SCHEMA_FIELD(CUtlVector<RnVertex_t>          , m_Vertices                                      , 0xB0) // CUtlVector<RnVertex_t>
        SCHEMA_FIELD(CUtlVector<RnHalfEdge_t>        , m_Edges                                         , 0xC8) // CUtlVector<RnHalfEdge_t>
        SCHEMA_FIELD(CUtlVector<RnFace_t>            , m_Faces                                         , 0xE0) // CUtlVector<RnFace_t>
    };

    // RnCompoundTree_t
    //   fields: 2
    //   size: 0x18
    //   @MGetKV3ClassDefaults
    class RnCompoundTree_t {
    public:
        SCHEMA_FIELD(CUtlLeanVector<RnCompoundTreeNode_t>, m_Nodes                                         , 0x0) // CUtlLeanVector<RnCompoundTreeNode_t>
        SCHEMA_FIELD(std::uint32_t                   , m_nStartIterationIndex                          , 0x10) // uint32
    };

    // VPhysEntityId_t
    //   fields: 1
    //   size: 0x4
    //   @MGetKV3ClassDefaults
    class VPhysEntityId_t {
    public:
        SCHEMA_FIELD(std::uint32_t                   , m_Id                                            , 0x0) // uint32
    };

    // FeFitMatrix_t
    //   fields: 5
    //   size: 0x40
    //   @MGetKV3ClassDefaults
    class FeFitMatrix_t {
    public:
        SCHEMA_FIELD(CTransform                      , bone                                            , 0x0) // CTransform
        SCHEMA_FIELD(::Vector                        , vCenter                                         , 0x20) // Vector
        SCHEMA_FIELD(std::uint16_t                   , nEnd                                            , 0x2C) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nNode                                           , 0x2E) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nBeginDynamic                                   , 0x30) // uint16
    };

    // FeAntiTunnelProbe_t
    //   fields: 8
    //   size: 0x1C
    //   @MGetKV3ClassDefaults
    class FeAntiTunnelProbe_t {
    public:
        SCHEMA_FIELD(float                           , flWeight                                        , 0x0) // float32
        SCHEMA_FIELD(std::uint32_t                   , nFlags                                          , 0x4) // uint32
        SCHEMA_FIELD(std::uint16_t                   , nProbeNode                                      , 0x8) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nCount                                          , 0xA) // uint16
        SCHEMA_FIELD(std::uint32_t                   , nBegin                                          , 0xC) // uint32
        SCHEMA_FIELD(float                           , flActivationDistance                            , 0x10) // float32
        SCHEMA_FIELD(float                           , flCurvatureRadius                               , 0x14) // float32
        SCHEMA_FIELD(float                           , flBias                                          , 0x18) // float32
    };

    // FourCovMatrices3
    //   fields: 4
    //   size: 0x60
    //   @MGetKV3ClassDefaults
    class FourCovMatrices3 {
    public:
        SCHEMA_FIELD(FourVectors                     , m_vDiag                                         , 0x0) // FourVectors
        SCHEMA_FIELD(fltx4                           , m_flXY                                          , 0x30) // fltx4
        SCHEMA_FIELD(fltx4                           , m_flXZ                                          , 0x40) // fltx4
        SCHEMA_FIELD(fltx4                           , m_flYZ                                          , 0x50) // fltx4
    };

    // RnCompoundDesc_t
    //   fields: 1
    //   size: 0x178
    //   @MGetKV3ClassDefaults
    class RnCompoundDesc_t {
    public:
        SCHEMA_FIELD(RnCompound_t                    , m_Compound                                      , 0x18) // RnCompound_t
    };

    // RnSoftbodyParticle_t
    //   fields: 1
    //   size: 0x4
    //   @MGetKV3ClassDefaults
    class RnSoftbodyParticle_t {
    public:
        SCHEMA_FIELD(float                           , m_flMassInv                                     , 0x0) // float32
    };

    // PhysFeModelDesc_t
    //   fields: 113
    //   size: 0x728
    //   @MGetKV3ClassDefaults
    class PhysFeModelDesc_t {
    public:
        SCHEMA_FIELD(CUtlVector<uint32>              , m_CtrlHash                                      , 0x0) // CUtlVector<uint32>
        SCHEMA_FIELD(CUtlVector<CUtlString>          , m_CtrlName                                      , 0x18) // CUtlVector<CUtlString>
        SCHEMA_FIELD(std::uint32_t                   , m_nStaticNodeFlags                              , 0x30) // uint32
        SCHEMA_FIELD(std::uint32_t                   , m_nDynamicNodeFlags                             , 0x34) // uint32
        SCHEMA_FIELD(float                           , m_flLocalForce                                  , 0x38) // float32
        SCHEMA_FIELD(float                           , m_flLocalRotation                               , 0x3C) // float32
        SCHEMA_FIELD(std::uint16_t                   , m_nNodeCount                                    , 0x40) // uint16
        SCHEMA_FIELD(std::uint16_t                   , m_nStaticNodes                                  , 0x42) // uint16
        SCHEMA_FIELD(std::uint16_t                   , m_nRotLockStaticNodes                           , 0x44) // uint16
        SCHEMA_FIELD(std::uint16_t                   , m_nFirstPositionDrivenNode                      , 0x46) // uint16
        SCHEMA_FIELD(std::uint16_t                   , m_nSimdTriCount1                                , 0x48) // uint16
        SCHEMA_FIELD(std::uint16_t                   , m_nSimdTriCount2                                , 0x4A) // uint16
        SCHEMA_FIELD(std::uint16_t                   , m_nSimdQuadCount1                               , 0x4C) // uint16
        SCHEMA_FIELD(std::uint16_t                   , m_nSimdQuadCount2                               , 0x4E) // uint16
        SCHEMA_FIELD(std::uint16_t                   , m_nQuadCount1                                   , 0x50) // uint16
        SCHEMA_FIELD(std::uint16_t                   , m_nQuadCount2                                   , 0x52) // uint16
        SCHEMA_FIELD(std::uint16_t                   , m_nTreeDepth                                    , 0x54) // uint16
        SCHEMA_FIELD(std::uint16_t                   , m_nNodeBaseJiggleboneDependsCount               , 0x56) // uint16
        SCHEMA_FIELD(std::uint16_t                   , m_nRopeCount                                    , 0x58) // uint16
        SCHEMA_FIELD(CUtlVector<uint16>              , m_Ropes                                         , 0x60) // CUtlVector<uint16>
        SCHEMA_FIELD(CUtlVector<FeNodeBase_t>        , m_NodeBases                                     , 0x78) // CUtlVector<FeNodeBase_t>
        SCHEMA_FIELD(CUtlVector<FeSimdNodeBase_t>    , m_SimdNodeBases                                 , 0x90) // CUtlVector<FeSimdNodeBase_t>
        SCHEMA_FIELD(CUtlVector<FeQuad_t>            , m_Quads                                         , 0xA8) // CUtlVector<FeQuad_t>
        SCHEMA_FIELD(CUtlVector<FeSimdQuad_t>        , m_SimdQuads                                     , 0xC0) // CUtlVector<FeSimdQuad_t>
        SCHEMA_FIELD(CUtlVector<FeSimdTri_t>         , m_SimdTris                                      , 0xD8) // CUtlVector<FeSimdTri_t>
        SCHEMA_FIELD(CUtlVector<FePrism_t>           , m_Prisms                                        , 0xF0) // CUtlVector<FePrism_t>
        SCHEMA_FIELD(CUtlVector<FeSimdPrism_t>       , m_SimdPrisms                                    , 0x108) // CUtlVector<FeSimdPrism_t>
        SCHEMA_FIELD(CUtlVector<FeSimdRodConstraint_t>, m_SimdRods                                      , 0x120) // CUtlVector<FeSimdRodConstraint_t>
        SCHEMA_FIELD(CUtlVector<FeSimdRodConstraintAnim_t>, m_SimdRodsAnim                                  , 0x138) // CUtlVector<FeSimdRodConstraintAnim_t>
        SCHEMA_FIELD(CUtlVector<CTransform>          , m_InitPose                                      , 0x150) // CUtlVector<CTransform>
        SCHEMA_FIELD(CUtlVector<FeRodConstraint_t>   , m_Rods                                          , 0x168) // CUtlVector<FeRodConstraint_t>
        SCHEMA_FIELD(CUtlVector<FeTwistConstraint_t> , m_Twists                                        , 0x180) // CUtlVector<FeTwistConstraint_t>
        SCHEMA_FIELD(CUtlVector<FeHingeLimit_t>      , m_HingeLimits                                   , 0x198) // CUtlVector<FeHingeLimit_t>
        SCHEMA_FIELD(CUtlVector<uint32>              , m_AntiTunnelBytecode                            , 0x1B0) // CUtlVector<uint32>
        SCHEMA_FIELD(CUtlVector<FeDynKinLink_t>      , m_DynKinLinks                                   , 0x1C8) // CUtlVector<FeDynKinLink_t>
        SCHEMA_FIELD(CUtlVector<FeBoneMergeLink_t>   , m_BoneMergeLinks                                , 0x1E0) // CUtlVector<FeBoneMergeLink_t>
        SCHEMA_FIELD(CUtlVector<FeAntiTunnelProbe_t> , m_AntiTunnelProbes                              , 0x1F8) // CUtlVector<FeAntiTunnelProbe_t>
        SCHEMA_FIELD(CUtlVector<uint16>              , m_AntiTunnelTargetNodes                         , 0x210) // CUtlVector<uint16>
        SCHEMA_FIELD(CUtlVector<FeNodeStrayBox_t>    , m_NodeStrayBoxes                                , 0x228) // CUtlVector<FeNodeStrayBox_t>
        SCHEMA_FIELD(CUtlVector<FeAxialEdgeBend_t>   , m_AxialEdges                                    , 0x240) // CUtlVector<FeAxialEdgeBend_t>
        SCHEMA_FIELD(CUtlVector<float32>             , m_NodeInvMasses                                 , 0x258) // CUtlVector<float32>
        SCHEMA_FIELD(CUtlVector<FeCtrlOffset_t>      , m_CtrlOffsets                                   , 0x270) // CUtlVector<FeCtrlOffset_t>
        SCHEMA_FIELD(CUtlVector<FeCtrlOsOffset_t>    , m_CtrlOsOffsets                                 , 0x288) // CUtlVector<FeCtrlOsOffset_t>
        SCHEMA_FIELD(CUtlVector<FeFollowNode_t>      , m_FollowNodes                                   , 0x2A0) // CUtlVector<FeFollowNode_t>
        SCHEMA_FIELD(CUtlVector<FeCollisionPlane_t>  , m_CollisionPlanes                               , 0x2B8) // CUtlVector<FeCollisionPlane_t>
        SCHEMA_FIELD(CUtlVector<FeNodeIntegrator_t>  , m_NodeIntegrator                                , 0x2D0) // CUtlVector<FeNodeIntegrator_t>
        SCHEMA_FIELD(CUtlVector<FeSpringIntegrator_t>, m_SpringIntegrator                              , 0x2E8) // CUtlVector<FeSpringIntegrator_t>
        SCHEMA_FIELD(CUtlVector<FeSimdSpringIntegrator_t>, m_SimdSpringIntegrator                          , 0x300) // CUtlVector<FeSimdSpringIntegrator_t>
        SCHEMA_FIELD(CUtlVector<FeWorldCollisionParams_t>, m_WorldCollisionParams                          , 0x318) // CUtlVector<FeWorldCollisionParams_t>
        SCHEMA_FIELD(CUtlVector<float32>             , m_LegacyStretchForce                            , 0x330) // CUtlVector<float32>
        SCHEMA_FIELD(CUtlVector<float32>             , m_NodeCollisionRadii                            , 0x348) // CUtlVector<float32>
        SCHEMA_FIELD(CUtlVector<float32>             , m_DynNodeFriction                               , 0x360) // CUtlVector<float32>
        SCHEMA_FIELD(CUtlVector<float32>             , m_LocalRotation                                 , 0x378) // CUtlVector<float32>
        SCHEMA_FIELD(CUtlVector<float32>             , m_LocalForce                                    , 0x390) // CUtlVector<float32>
        SCHEMA_FIELD(CUtlVector<FeTaperedCapsuleStretch_t>, m_TaperedCapsuleStretches                       , 0x3A8) // CUtlVector<FeTaperedCapsuleStretch_t>
        SCHEMA_FIELD(CUtlVector<FeTaperedCapsuleRigid_t>, m_TaperedCapsuleRigids                          , 0x3C0) // CUtlVector<FeTaperedCapsuleRigid_t>
        SCHEMA_FIELD(CUtlVector<FeSphereRigid_t>     , m_SphereRigids                                  , 0x3D8) // CUtlVector<FeSphereRigid_t>
        SCHEMA_FIELD(CUtlVector<uint16>              , m_WorldCollisionNodes                           , 0x3F0) // CUtlVector<uint16>
        SCHEMA_FIELD(CUtlVector<uint16>              , m_TreeParents                                   , 0x408) // CUtlVector<uint16>
        SCHEMA_FIELD(CUtlVector<uint16>              , m_TreeCollisionMasks                            , 0x420) // CUtlVector<uint16>
        SCHEMA_FIELD(CUtlVector<FeTreeChildren_t>    , m_TreeChildren                                  , 0x438) // CUtlVector<FeTreeChildren_t>
        SCHEMA_FIELD(CUtlVector<uint16>              , m_FreeNodes                                     , 0x450) // CUtlVector<uint16>
        SCHEMA_FIELD(CUtlVector<FeFitMatrix_t>       , m_FitMatrices                                   , 0x468) // CUtlVector<FeFitMatrix_t>
        SCHEMA_FIELD(CUtlVector<FeFitWeight_t>       , m_FitWeights                                    , 0x480) // CUtlVector<FeFitWeight_t>
        SCHEMA_FIELD(CUtlVector<FeNodeReverseOffset_t>, m_ReverseOffsets                                , 0x498) // CUtlVector<FeNodeReverseOffset_t>
        SCHEMA_FIELD(CUtlVector<FeAnimStrayRadius_t> , m_AnimStrayRadii                                , 0x4B0) // CUtlVector<FeAnimStrayRadius_t>
        SCHEMA_FIELD(CUtlVector<FeSimdAnimStrayRadius_t>, m_SimdAnimStrayRadii                            , 0x4C8) // CUtlVector<FeSimdAnimStrayRadius_t>
        SCHEMA_FIELD(CUtlVector<FeKelagerBend2_t>    , m_KelagerBends                                  , 0x4E0) // CUtlVector<FeKelagerBend2_t>
        SCHEMA_FIELD(CUtlVector<FeCtrlSoftOffset_t>  , m_CtrlSoftOffsets                               , 0x4F8) // CUtlVector<FeCtrlSoftOffset_t>
        SCHEMA_FIELD(CUtlVector<CFeIndexedJiggleBone>, m_JiggleBones                                   , 0x510) // CUtlVector<CFeIndexedJiggleBone>
        SCHEMA_FIELD(CUtlVector<uint16>              , m_SourceElems                                   , 0x528) // CUtlVector<uint16>
        SCHEMA_FIELD(CUtlVector<uint32>              , m_GoalDampedSpringIntegrators                   , 0x540) // CUtlVector<uint32>
        SCHEMA_FIELD(CUtlVector<FeTri_t>             , m_Tris                                          , 0x558) // CUtlVector<FeTri_t>
        SCHEMA_FIELD(std::uint16_t                   , m_nTriCount1                                    , 0x570) // uint16
        SCHEMA_FIELD(std::uint16_t                   , m_nTriCount2                                    , 0x572) // uint16
        SCHEMA_FIELD(std::uint8_t                    , m_nReservedUint8                                , 0x574) // uint8
        SCHEMA_FIELD(std::uint8_t                    , m_nExtraPressureIterations                      , 0x575) // uint8
        SCHEMA_FIELD(std::uint8_t                    , m_nExtraGoalIterations                          , 0x576) // uint8
        SCHEMA_FIELD(std::uint8_t                    , m_nExtraIterations                              , 0x577) // uint8
        SCHEMA_FIELD(CUtlVector<FeSDFRigid_t>        , m_SDFRigids                                     , 0x578) // CUtlVector<FeSDFRigid_t>
        SCHEMA_FIELD(CUtlVector<FeBoxRigid_t>        , m_BoxRigids                                     , 0x590) // CUtlVector<FeBoxRigid_t>
        SCHEMA_FIELD(CUtlVector<uint8>               , m_DynNodeVertexSet                              , 0x5A8) // CUtlVector<uint8>
        SCHEMA_FIELD(CUtlVector<uint32>              , m_VertexSetNames                                , 0x5C0) // CUtlVector<uint32>
        SCHEMA_FIELD(CUtlVector<FeRigidColliderIndices_t>, m_RigidColliderPriorities                       , 0x5D8) // CUtlVector<FeRigidColliderIndices_t>
        SCHEMA_FIELD(CUtlVector<FeMorphLayerDepr_t>  , m_MorphLayers                                   , 0x5F0) // CUtlVector<FeMorphLayerDepr_t>
        SCHEMA_FIELD(CUtlVector<uint8>               , m_MorphSetData                                  , 0x608) // CUtlVector<uint8>
        SCHEMA_FIELD(CUtlVector<FeVertexMapDesc_t>   , m_VertexMaps                                    , 0x620) // CUtlVector<FeVertexMapDesc_t>
        SCHEMA_FIELD(CUtlVector<uint8>               , m_VertexMapValues                               , 0x638) // CUtlVector<uint8>
        SCHEMA_FIELD(CUtlVector<FeEffectDesc_t>      , m_Effects                                       , 0x650) // CUtlVector<FeEffectDesc_t>
        SCHEMA_FIELD(CUtlVector<FeCtrlOffset_t>      , m_LockToParent                                  , 0x668) // CUtlVector<FeCtrlOffset_t>
        SCHEMA_FIELD(CUtlVector<uint16>              , m_LockToGoal                                    , 0x680) // CUtlVector<uint16>
        SCHEMA_FIELD(CUtlVector<int16>               , m_SkelParents                                   , 0x698) // CUtlVector<int16>
        SCHEMA_FIELD(CUtlVector<FeNodeWindBase_t>    , m_DynNodeWindBases                              , 0x6B0) // CUtlVector<FeNodeWindBase_t>
        SCHEMA_FIELD(CUtlVector<FeModelSelfCollisionLayer_t>, m_SelfCollisionLayers                           , 0x6C8) // CUtlVector<FeModelSelfCollisionLayer_t>
        SCHEMA_FIELD(float                           , m_flInternalPressure                            , 0x6E0) // float32
        SCHEMA_FIELD(float                           , m_flDefaultTimeDilation                         , 0x6E4) // float32
        SCHEMA_FIELD(float                           , m_flWindage                                     , 0x6E8) // float32
        SCHEMA_FIELD(float                           , m_flWindDrag                                    , 0x6EC) // float32
        SCHEMA_FIELD(float                           , m_flDefaultSurfaceStretch                       , 0x6F0) // float32
        SCHEMA_FIELD(float                           , m_flDefaultThreadStretch                        , 0x6F4) // float32
        SCHEMA_FIELD(float                           , m_flDefaultGravityScale                         , 0x6F8) // float32
        SCHEMA_FIELD(float                           , m_flDefaultVelAirDrag                           , 0x6FC) // float32
        SCHEMA_FIELD(float                           , m_flDefaultExpAirDrag                           , 0x700) // float32
        SCHEMA_FIELD(float                           , m_flDefaultVelQuadAirDrag                       , 0x704) // float32
        SCHEMA_FIELD(float                           , m_flDefaultExpQuadAirDrag                       , 0x708) // float32
        SCHEMA_FIELD(float                           , m_flRodVelocitySmoothRate                       , 0x70C) // float32
        SCHEMA_FIELD(float                           , m_flQuadVelocitySmoothRate                      , 0x710) // float32
        SCHEMA_FIELD(float                           , m_flAddWorldCollisionRadius                     , 0x714) // float32
        SCHEMA_FIELD(float                           , m_flDefaultVolumetricSolveAmount                , 0x718) // float32
        SCHEMA_FIELD(float                           , m_flMotionSmoothCDT                             , 0x71C) // float32
        SCHEMA_FIELD(float                           , m_flLocalDrag1                                  , 0x720) // float32
        SCHEMA_FIELD(std::uint16_t                   , m_nRodVelocitySmoothIterations                  , 0x724) // uint16
        SCHEMA_FIELD(std::uint16_t                   , m_nQuadVelocitySmoothIterations                 , 0x726) // uint16
    };

    // FeSpringIntegrator_t
    //   fields: 5
    //   size: 0x14
    //   @MGetKV3ClassDefaults
    class FeSpringIntegrator_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , nNode                                           , 0x0) // uint16[2]
        SCHEMA_FIELD(float                           , flSpringRestLength                              , 0x4) // float32
        SCHEMA_FIELD(float                           , flSpringConstant                                , 0x8) // float32
        SCHEMA_FIELD(float                           , flSpringDamping                                 , 0xC) // float32
        SCHEMA_FIELD(float                           , flNodeWeight0                                   , 0x10) // float32
    };

    // FeFitWeight_t
    //   fields: 3
    //   size: 0x8
    //   @MGetKV3ClassDefaults
    class FeFitWeight_t {
    public:
        SCHEMA_FIELD(float                           , flWeight                                        , 0x0) // float32
        SCHEMA_FIELD(std::uint16_t                   , nNode                                           , 0x4) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nDummy                                          , 0x6) // uint16
    };

    // CFeMorphLayer
    //   fields: 7
    //   size: 0x88
    //   @MGetKV3ClassDefaults
    class CFeMorphLayer {
    public:
        SCHEMA_FIELD(::CUtlString                    , m_Name                                          , 0x0) // CUtlString
        SCHEMA_FIELD(std::uint32_t                   , m_nNameHash                                     , 0x8) // uint32
        SCHEMA_FIELD(CUtlVector<uint16>              , m_Nodes                                         , 0x10) // CUtlVector<uint16>
        SCHEMA_FIELD(CUtlVector<Vector>              , m_InitPos                                       , 0x28) // CUtlVector<Vector>
        SCHEMA_FIELD(CUtlVector<float32>             , m_Gravity                                       , 0x40) // CUtlVector<float32>
        SCHEMA_FIELD(CUtlVector<float32>             , m_GoalStrength                                  , 0x58) // CUtlVector<float32>
        SCHEMA_FIELD(CUtlVector<float32>             , m_GoalDamping                                   , 0x70) // CUtlVector<float32>
    };

    // IPhysicsRagdollControl
    //   fields: 0
    //   size: 0x8
    class IPhysicsRagdollControl {
    public:
    };

    // VertexPositionNormal_t
    //   fields: 2
    //   size: 0x18
    class VertexPositionNormal_t {
    public:
        SCHEMA_FIELD(::Vector                        , m_vPosition                                     , 0x0) // Vector
        SCHEMA_FIELD(::Vector                        , m_vNormal                                       , 0xC) // Vector
    };

    // FeBuildTaperedCapsuleRigid_t
    //   fields: 3
    //   size: 0x40
    //   @MGetKV3ClassDefaults
    class FeBuildTaperedCapsuleRigid_t {
    public:
        SCHEMA_FIELD(std::int32_t                    , m_nPriority                                     , 0x30) // int32
        SCHEMA_FIELD(std::uint32_t                   , m_nVertexMapHash                                , 0x34) // uint32
        SCHEMA_FIELD(std::uint32_t                   , m_nAntitunnelGroupBits                          , 0x38) // uint32
    };

    // FeCtrlOsOffset_t
    //   fields: 2
    //   size: 0x4
    //   @MGetKV3ClassDefaults
    class FeCtrlOsOffset_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , nCtrlParent                                     , 0x0) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nCtrlChild                                      , 0x2) // uint16
    };

    // RnCapsuleDesc_t
    //   fields: 1
    //   size: 0x38
    //   @MGetKV3ClassDefaults
    class RnCapsuleDesc_t {
    public:
        SCHEMA_FIELD(RnCapsule_t                     , m_Capsule                                       , 0x18) // RnCapsule_t
    };

    // FeAnimStrayRadius_t
    //   fields: 3
    //   size: 0xC
    //   @MGetKV3ClassDefaults
    class FeAnimStrayRadius_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , nNode                                           , 0x0) // uint16[2]
        SCHEMA_FIELD(float                           , flMaxDist                                       , 0x4) // float32
        SCHEMA_FIELD(float                           , flRelaxationFactor                              , 0x8) // float32
    };

    // FeDynKinLink_t
    //   fields: 2
    //   size: 0x4
    //   @MGetKV3ClassDefaults
    class FeDynKinLink_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , m_nParent                                       , 0x0) // uint16
        SCHEMA_FIELD(std::uint16_t                   , m_nChild                                        , 0x2) // uint16
    };

    // FeTwistConstraint_t
    //   fields: 4
    //   size: 0xC
    //   @MGetKV3ClassDefaults
    class FeTwistConstraint_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , nNodeOrient                                     , 0x0) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nNodeEnd                                        , 0x2) // uint16
        SCHEMA_FIELD(float                           , flTwistRelax                                    , 0x4) // float32
        SCHEMA_FIELD(float                           , flSwingRelax                                    , 0x8) // float32
    };

    // RnMesh_t
    //   fields: 12
    //   size: 0xC0
    //   @MGetKV3ClassDefaults
    class RnMesh_t {
    public:
        SCHEMA_FIELD(::Vector                        , m_vMin                                          , 0x0) // Vector
        SCHEMA_FIELD(::Vector                        , m_vMax                                          , 0xC) // Vector
        SCHEMA_FIELD(CUtlVector<RnNode_t>            , m_Nodes                                         , 0x18) // CUtlVector<RnNode_t>
        SCHEMA_FIELD(CUtlVectorSIMDPaddedVector      , m_Vertices                                      , 0x30) // CUtlVectorSIMDPaddedVector
        SCHEMA_FIELD(CUtlVector<RnTriangle_t>        , m_Triangles                                     , 0x48) // CUtlVector<RnTriangle_t>
        SCHEMA_FIELD(CUtlVector<RnWing_t>            , m_Wings                                         , 0x60) // CUtlVector<RnWing_t>
        SCHEMA_FIELD(CUtlVector<uint8>               , m_TriangleEdgeFlags                             , 0x78) // CUtlVector<uint8>
        SCHEMA_FIELD(CUtlVector<uint8>               , m_Materials                                     , 0x90) // CUtlVector<uint8>
        SCHEMA_FIELD(::Vector                        , m_vOrthographicAreas                            , 0xA8) // Vector
        SCHEMA_FIELD(std::uint32_t                   , m_nFlags                                        , 0xB4) // uint32
        SCHEMA_FIELD(std::uint32_t                   , m_nDebugFlags                                   , 0xB8) // uint32
        SCHEMA_FIELD(float                           , m_flSurfaceArea                                 , 0xBC) // float32
    };

    // FeEdgeDesc_t
    //   fields: 3
    //   size: 0x10
    //   @MGetKV3ClassDefaults
    class FeEdgeDesc_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , nEdge                                           , 0x0) // uint16[2]
        SCHEMA_FIELD(std::uint16_t                   , nSide                                           , 0x4) // uint16[2][2]
        SCHEMA_FIELD(std::uint16_t                   , nVirtElem                                       , 0xC) // uint16[2]
    };

    // CRegionSVM
    //   fields: 2
    //   size: 0x30
    //   @MGetKV3ClassDefaults
    class CRegionSVM {
    public:
        SCHEMA_FIELD(CUtlVector<RnPlane_t>           , m_Planes                                        , 0x0) // CUtlVector<RnPlane_t>
        SCHEMA_FIELD(CUtlVector<uint32>              , m_Nodes                                         , 0x18) // CUtlVector<uint32>
    };

    // FeProxyVertexMap_t
    //   fields: 2
    //   size: 0x10
    //   @MGetKV3ClassDefaults
    class FeProxyVertexMap_t {
    public:
        SCHEMA_FIELD(::CUtlString                    , m_Name                                          , 0x0) // CUtlString
        SCHEMA_FIELD(float                           , m_flWeight                                      , 0x8) // float32
    };

    // CGenericShapeProxy
    //   fields: 1
    //   size: 0x98
    class CGenericShapeProxy {
    public:
        using _Type0 = CUtlLeanVectorFixedGrowable<Vector,8>;
        SCHEMA_FIELD(_Type0                          , m_verts                                         , 0x30) // CUtlLeanVectorFixedGrowable<Vector,8>
    };

    // RnNode_t
    //   fields: 4
    //   size: 0x20
    //   @MGetKV3ClassDefaults
    class RnNode_t {
    public:
        SCHEMA_FIELD(::Vector                        , m_vMin                                          , 0x0) // Vector
        SCHEMA_FIELD(std::uint32_t                   , m_nChildren                                     , 0xC) // uint32
        SCHEMA_FIELD(::Vector                        , m_vMax                                          , 0x10) // Vector
        SCHEMA_FIELD(std::uint32_t                   , m_nTriangleOffset                               , 0x1C) // uint32
    };

    // CollisionDetailLayerInfo_t
    //   fields: 6
    //   size: 0x40
    //   @MGetKV3ClassDefaults
    //   @MVDataOutlinerLeafNameFn
    class CollisionDetailLayerInfo_t {
    public:
        SCHEMA_FIELD(::CUtlString                    , m_sDescription                                  , 0x0) // CUtlString [MPropertyFriendlyName, MPropertyDescription]
        SCHEMA_FIELD(::CUtlString                    , m_sFriendlyName                                 , 0x8) // CUtlString [MPropertyFriendlyName, MPropertyDescription]
        SCHEMA_FIELD(bool                            , m_bIsQueryOnly                                  , 0x10) // bool [MPropertyDescription]
        SCHEMA_FIELD(::CUtlString                    , m_sParentDetailLayer                            , 0x18) // CUtlString [MPropertyDescription]
        SCHEMA_FIELD(CUtlVector<CollisionDetailLayerInfo_t_Name_t>, m_vecSubtreeDetailLayers                        , 0x20) // CUtlVector<CollisionDetailLayerInfo_t::Name_t> [MPropertySuppressField]
        SCHEMA_FIELD(bool                            , m_bNotPickable                                  , 0x38) // bool [MPropertySuppressField]
    };

    // IPhysicsPlayerController
    //   fields: 0
    //   size: 0x8
    class IPhysicsPlayerController {
    public:
    };

    // RnMeshDesc_t
    //   fields: 1
    //   size: 0xD8
    //   @MGetKV3ClassDefaults
    class RnMeshDesc_t {
    public:
        SCHEMA_FIELD(RnMesh_t                        , m_Mesh                                          , 0x18) // RnMesh_t
    };

    // RnSphereDesc_t
    //   fields: 1
    //   size: 0x28
    //   @MGetKV3ClassDefaults
    class RnSphereDesc_t {
    public:
        SCHEMA_FIELD(RnSphere_t                      , m_Sphere                                        , 0x18) // RnSphere_t
    };

    // RnSoftbodyCapsule_t
    //   fields: 3
    //   size: 0x20
    //   @MGetKV3ClassDefaults
    class RnSoftbodyCapsule_t {
    public:
        SCHEMA_FIELD(::Vector                        , m_vCenter                                       , 0x0) // Vector[2]
        SCHEMA_FIELD(float                           , m_flRadius                                      , 0x18) // float32
        SCHEMA_FIELD(std::uint16_t                   , m_nParticle                                     , 0x1C) // uint16[2]
    };

    // FeSimdAnimStrayRadius_t
    //   fields: 3
    //   size: 0x30
    //   @MGetKV3ClassDefaults
    class FeSimdAnimStrayRadius_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , nNode                                           , 0x0) // uint16[4][2]
        SCHEMA_FIELD(fltx4                           , flMaxDist                                       , 0x10) // fltx4
        SCHEMA_FIELD(fltx4                           , flRelaxationFactor                              , 0x20) // fltx4
    };

    // FeHingeLimitBuild_t
    //   fields: 4
    //   size: 0x18
    //   @MGetKV3ClassDefaults
    class FeHingeLimitBuild_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , nNode                                           , 0x0) // uint16[6]
        SCHEMA_FIELD(std::uint32_t                   , nFlags                                          , 0xC) // uint32
        SCHEMA_FIELD(float                           , flLimitCW                                       , 0x10) // float32
        SCHEMA_FIELD(float                           , flLimitCCW                                      , 0x14) // float32
    };

    // RnShapeDesc_t
    //   fields: 6
    //   size: 0x18
    //   @MGetKV3ClassDefaults
    class RnShapeDesc_t {
    public:
        SCHEMA_FIELD(std::uint32_t                   , m_nCollisionAttributeIndex                      , 0x0) // uint32
        SCHEMA_FIELD(std::uint32_t                   , m_nSurfacePropertyIndex                         , 0x4) // uint32
        SCHEMA_FIELD(::CUtlString                    , m_UserFriendlyName                              , 0x8) // CUtlString
        SCHEMA_FIELD(bool                            , m_bUserFriendlyNameSealed                       , 0x10) // bool
        SCHEMA_FIELD(bool                            , m_bUserFriendlyNameLong                         , 0x11) // bool
        SCHEMA_FIELD(std::uint32_t                   , m_nToolMaterialHash                             , 0x14) // uint32
    };

    // RnHalfEdge_t
    //   fields: 4
    //   size: 0x4
    //   @MGetKV3ClassDefaults
    class RnHalfEdge_t {
    public:
        SCHEMA_FIELD(std::uint8_t                    , m_nNext                                         , 0x0) // uint8
        SCHEMA_FIELD(std::uint8_t                    , m_nTwin                                         , 0x1) // uint8
        SCHEMA_FIELD(std::uint8_t                    , m_nOrigin                                       , 0x2) // uint8
        SCHEMA_FIELD(std::uint8_t                    , m_nFace                                         , 0x3) // uint8
    };

    // RnBodyDesc_t
    //   fields: 36
    //   size: 0xE0
    //   @MGetKV3ClassDefaults
    class RnBodyDesc_t {
    public:
        SCHEMA_FIELD(::CUtlString                    , m_sDebugName                                    , 0x0) // CUtlString
        SCHEMA_FIELD(VectorWS                        , m_vPosition                                     , 0x8) // VectorWS
        SCHEMA_FIELD(QuaternionStorage               , m_qOrientation                                  , 0x14) // QuaternionStorage
        SCHEMA_FIELD(::Vector                        , m_vLinearVelocity                               , 0x24) // Vector
        SCHEMA_FIELD(::Vector                        , m_vAngularVelocity                              , 0x30) // Vector
        SCHEMA_FIELD(::Vector                        , m_vLocalMassCenter                              , 0x3C) // Vector
        SCHEMA_FIELD(::Vector                        , m_LocalInertiaInv                               , 0x48) // Vector[3]
        SCHEMA_FIELD(float                           , m_flMassInv                                     , 0x6C) // float32
        SCHEMA_FIELD(float                           , m_flGameMass                                    , 0x70) // float32
        SCHEMA_FIELD(float                           , m_flMassScaleInv                                , 0x74) // float32
        SCHEMA_FIELD(float                           , m_flInertiaScaleInv                             , 0x78) // float32
        SCHEMA_FIELD(float                           , m_flLinearDamping                               , 0x7C) // float32
        SCHEMA_FIELD(float                           , m_flAngularDamping                              , 0x80) // float32
        SCHEMA_FIELD(float                           , m_flLinearDragScale                             , 0x84) // float32
        SCHEMA_FIELD(float                           , m_flAngularDragScale                            , 0x88) // float32
        SCHEMA_FIELD(float                           , m_flLinearFluidDragScale                        , 0x8C) // float32
        SCHEMA_FIELD(float                           , m_flAngularFluidDragScale                       , 0x90) // float32
        SCHEMA_FIELD(::Vector                        , m_vLastAwakeForceAccum                          , 0x94) // Vector
        SCHEMA_FIELD(::Vector                        , m_vLastAwakeTorqueAccum                         , 0xA0) // Vector
        SCHEMA_FIELD(float                           , m_flBuoyancyScale                               , 0xAC) // float32
        SCHEMA_FIELD(float                           , m_flGravityScale                                , 0xB0) // float32
        SCHEMA_FIELD(float                           , m_flTimeScale                                   , 0xB4) // float32
        SCHEMA_FIELD(std::int32_t                    , m_nBodyType                                     , 0xB8) // int32
        SCHEMA_FIELD(std::uint32_t                   , m_nGameIndex                                    , 0xBC) // uint32
        SCHEMA_FIELD(std::uint32_t                   , m_nGameFlags                                    , 0xC0) // uint32
        SCHEMA_FIELD(std::int8_t                     , m_nMinVelocityIterations                        , 0xC4) // int8
        SCHEMA_FIELD(std::int8_t                     , m_nMinPositionIterations                        , 0xC5) // int8
        SCHEMA_FIELD(std::int8_t                     , m_nMassPriority                                 , 0xC6) // int8
        SCHEMA_FIELD(bool                            , m_bEnabled                                      , 0xC7) // bool
        SCHEMA_FIELD(bool                            , m_bSleeping                                     , 0xC8) // bool
        SCHEMA_FIELD(bool                            , m_bIsContinuousEnabled                          , 0xC9) // bool
        SCHEMA_FIELD(bool                            , m_bDragEnabled                                  , 0xCA) // bool
        SCHEMA_FIELD(::Vector                        , m_vGravity                                      , 0xCC) // Vector
        SCHEMA_FIELD(bool                            , m_bSpeculativeEnabled                           , 0xD8) // bool
        SCHEMA_FIELD(bool                            , m_bHasShadowController                          , 0xD9) // bool
        SCHEMA_FIELD(DynamicContinuousContactBehavior_t, m_nDynamicContinuousContactBehavior             , 0xDA) // DynamicContinuousContactBehavior_t
    };

    // RnPlane_t
    //   fields: 2
    //   size: 0x10
    //   @MGetKV3ClassDefaults
    class RnPlane_t {
    public:
        SCHEMA_FIELD(::Vector                        , m_vNormal                                       , 0x0) // Vector
        SCHEMA_FIELD(float                           , m_flOffset                                      , 0xC) // float32
    };

    // FeQuad_t
    //   fields: 3
    //   size: 0x4C
    //   @MGetKV3ClassDefaults
    class FeQuad_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , nNode                                           , 0x0) // uint16[4]
        SCHEMA_FIELD(float                           , flSlack                                         , 0x8) // float32
        SCHEMA_FIELD(::Vector4D                      , vShape                                          , 0xC) // Vector4D[4]
    };

    // FeAntiTunnelGroupBuild_t
    //   fields: 2
    //   size: 0x8
    //   @MGetKV3ClassDefaults
    class FeAntiTunnelGroupBuild_t {
    public:
        SCHEMA_FIELD(std::uint32_t                   , m_nVertexMapHash                                , 0x0) // uint32
        SCHEMA_FIELD(std::uint32_t                   , m_nCollisionMask                                , 0x4) // uint32
    };

    // FeFitInfluence_t
    //   fields: 3
    //   size: 0xC
    //   @MGetKV3ClassDefaults
    class FeFitInfluence_t {
    public:
        SCHEMA_FIELD(std::uint32_t                   , nVertexNode                                     , 0x0) // uint32
        SCHEMA_FIELD(float                           , flWeight                                        , 0x4) // float32
        SCHEMA_FIELD(std::uint32_t                   , nMatrixNode                                     , 0x8) // uint32
    };

    // FeMorphLayerDepr_t
    //   fields: 8
    //   size: 0x90
    //   @MGetKV3ClassDefaults
    class FeMorphLayerDepr_t {
    public:
        SCHEMA_FIELD(::CUtlString                    , m_Name                                          , 0x0) // CUtlString
        SCHEMA_FIELD(std::uint32_t                   , m_nNameHash                                     , 0x8) // uint32
        SCHEMA_FIELD(CUtlVector<uint16>              , m_Nodes                                         , 0x10) // CUtlVector<uint16>
        SCHEMA_FIELD(CUtlVector<Vector>              , m_InitPos                                       , 0x28) // CUtlVector<Vector>
        SCHEMA_FIELD(CUtlVector<float32>             , m_Gravity                                       , 0x40) // CUtlVector<float32>
        SCHEMA_FIELD(CUtlVector<float32>             , m_GoalStrength                                  , 0x58) // CUtlVector<float32>
        SCHEMA_FIELD(CUtlVector<float32>             , m_GoalDamping                                   , 0x70) // CUtlVector<float32>
        SCHEMA_FIELD(std::uint32_t                   , m_nFlags                                        , 0x88) // uint32
    };

    // FeSimdRodConstraintAnim_t
    //   fields: 3
    //   size: 0x30
    //   @MGetKV3ClassDefaults
    class FeSimdRodConstraintAnim_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , nNode                                           , 0x0) // uint16[4][2]
        SCHEMA_FIELD(fltx4                           , f4Weight0                                       , 0x10) // fltx4
        SCHEMA_FIELD(fltx4                           , f4RelaxationFactor                              , 0x20) // fltx4
    };

    // RnVertex_t
    //   fields: 1
    //   size: 0x1
    //   @MGetKV3ClassDefaults
    class RnVertex_t {
    public:
        SCHEMA_FIELD(std::uint8_t                    , m_nEdge                                         , 0x0) // uint8
    };

    // FeSourceEdge_t
    //   fields: 1
    //   size: 0x4
    //   @MGetKV3ClassDefaults
    class FeSourceEdge_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , nNode                                           , 0x0) // uint16[2]
    };

    // FeWeightedNode_t
    //   fields: 2
    //   size: 0x4
    //   @MGetKV3ClassDefaults
    class FeWeightedNode_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , nNode                                           , 0x0) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nWeight                                         , 0x2) // uint16
    };

    // FeWorldCollisionParams_t
    //   fields: 4
    //   size: 0xC
    //   @MGetKV3ClassDefaults
    class FeWorldCollisionParams_t {
    public:
        SCHEMA_FIELD(float                           , flWorldFriction                                 , 0x0) // float32
        SCHEMA_FIELD(float                           , flGroundFriction                                , 0x4) // float32
        SCHEMA_FIELD(std::uint16_t                   , nListBegin                                      , 0x8) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nListEnd                                        , 0xA) // uint16
    };

    // FeEffectDesc_t
    //   fields: 4
    //   size: 0x20
    //   @MGetKV3ClassDefaults
    class FeEffectDesc_t {
    public:
        SCHEMA_FIELD(::CUtlString                    , sName                                           , 0x0) // CUtlString
        SCHEMA_FIELD(std::uint32_t                   , nNameHash                                       , 0x8) // uint32
        SCHEMA_FIELD(std::int32_t                    , nType                                           , 0xC) // int32
        SCHEMA_FIELD(KeyValues3                      , m_Params                                        , 0x10) // KeyValues3
    };

    // FeModelSelfCollisionLayer_t
    //   fields: 5
    //   size: 0x38
    //   @MGetKV3ClassDefaults
    class FeModelSelfCollisionLayer_t {
    public:
        SCHEMA_FIELD(::CUtlString                    , m_Name                                          , 0x0) // CUtlString
        SCHEMA_FIELD(CUtlVector<uint16>              , m_Nodes                                         , 0x8) // CUtlVector<uint16>
        SCHEMA_FIELD(float                           , m_flParentReaction                              , 0x20) // float32
        SCHEMA_FIELD(std::uint32_t                   , m_nFlags                                        , 0x24) // uint32
        SCHEMA_FIELD(std::uint32_t                   , m_nEndIdx                                       , 0x28) // uint32[4]
    };

    // FeSimdPrism_t
    //   fields: 2
    //   size: 0x40
    //   @MGetKV3ClassDefaults
    class FeSimdPrism_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , nNode                                           , 0x0) // uint16[4][6]
        SCHEMA_FIELD(fltx4                           , flVolume                                        , 0x30) // fltx4
    };

    // FeAntiTunnelProbeBuild_t
    //   fields: 7
    //   size: 0x30
    //   @MGetKV3ClassDefaults
    class FeAntiTunnelProbeBuild_t {
    public:
        SCHEMA_FIELD(float                           , flWeight                                        , 0x0) // float32
        SCHEMA_FIELD(float                           , flActivationDistance                            , 0x4) // float32
        SCHEMA_FIELD(float                           , flBias                                          , 0x8) // float32
        SCHEMA_FIELD(float                           , flCurvature                                     , 0xC) // float32
        SCHEMA_FIELD(std::uint32_t                   , nFlags                                          , 0x10) // uint32
        SCHEMA_FIELD(std::uint16_t                   , nProbeNode                                      , 0x14) // uint16
        SCHEMA_FIELD(CUtlVector<uint16>              , targetNodes                                     , 0x18) // CUtlVector<uint16>
    };

    // RnCompoundTreeNode_t
    //   fields: 4
    //   size: 0x1C
    //   @MGetKV3ClassDefaults
    class RnCompoundTreeNode_t {
    public:
        SCHEMA_FIELD(::Vector                        , m_vMin                                          , 0x0) // Vector
        SCHEMA_FIELD(::Vector                        , m_vMax                                          , 0xC) // Vector
        // SKIPPED: m_nType (bitfield type not supported)
        // SKIPPED: m_nSubtreeEndOrCompoundId (bitfield type not supported)
    };

    // FeTaperedCapsuleStretch_t
    //   fields: 4
    //   size: 0x10
    //   @MGetKV3ClassDefaults
    class FeTaperedCapsuleStretch_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , nNode                                           , 0x0) // uint16[2]
        SCHEMA_FIELD(std::uint16_t                   , nCollisionMask                                  , 0x4) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nDummy                                          , 0x6) // uint16 [MPropertySuppressField]
        SCHEMA_FIELD(float                           , flRadius                                        , 0x8) // float32[2]
    };

    // FeCtrlOffset_t
    //   fields: 3
    //   size: 0x10
    //   @MGetKV3ClassDefaults
    class FeCtrlOffset_t {
    public:
        SCHEMA_FIELD(::Vector                        , vOffset                                         , 0x0) // Vector
        SCHEMA_FIELD(std::uint16_t                   , nCtrlParent                                     , 0xC) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nCtrlChild                                      , 0xE) // uint16
    };

    // FeBuildSDFRigid_t
    //   fields: 3
    //   size: 0x60
    //   @MGetKV3ClassDefaults
    class FeBuildSDFRigid_t {
    public:
        SCHEMA_FIELD(std::int32_t                    , m_nPriority                                     , 0x50) // int32
        SCHEMA_FIELD(std::uint32_t                   , m_nVertexMapHash                                , 0x54) // uint32
        SCHEMA_FIELD(std::uint32_t                   , m_nAntitunnelGroupBits                          , 0x58) // uint32
    };

    // FeSimdQuad_t
    //   fields: 4
    //   size: 0x130
    //   @MGetKV3ClassDefaults
    class FeSimdQuad_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , nNode                                           , 0x0) // uint16[4][4]
        SCHEMA_FIELD(fltx4                           , f4Slack                                         , 0x20) // fltx4
        SCHEMA_FIELD(FourVectors                     , vShape                                          , 0x30) // FourVectors[4]
        SCHEMA_FIELD(fltx4                           , f4Weights                                       , 0xF0) // fltx4[4]
    };

    // CFeNamedJiggleBone
    //   fields: 4
    //   size: 0xD0
    //   @MGetKV3ClassDefaults
    class CFeNamedJiggleBone {
    public:
        SCHEMA_FIELD(::CUtlString                    , m_strParentBone                                 , 0x0) // CUtlString
        SCHEMA_FIELD(CTransform                      , m_transform                                     , 0x10) // CTransform
        SCHEMA_FIELD(std::uint32_t                   , m_nJiggleParent                                 , 0x30) // uint32
        SCHEMA_FIELD(CFeJiggleBone                   , m_jiggleBone                                    , 0x34) // CFeJiggleBone
    };

    // IPhysAggregateInstance
    //   fields: 2
    //   size: 0x18
    class IPhysAggregateInstance {
    public:
        SCHEMA_FIELD(void*                           , m_pSkeleton                                     , 0x8) // void*
        SCHEMA_FIELD(bool                            , m_bIsAxisAligned                                , 0x10) // bool
    };

    // FeBuildSphereRigid_t
    //   fields: 3
    //   size: 0x30
    //   @MGetKV3ClassDefaults
    class FeBuildSphereRigid_t {
    public:
        SCHEMA_FIELD(std::int32_t                    , m_nPriority                                     , 0x20) // int32
        SCHEMA_FIELD(std::uint32_t                   , m_nVertexMapHash                                , 0x24) // uint32
        SCHEMA_FIELD(std::uint32_t                   , m_nAntitunnelGroupBits                          , 0x28) // uint32
    };

    // RnCompound_t
    //   fields: 13
    //   size: 0x160
    //   @MGetKV3ClassDefaults
    class RnCompound_t {
    public:
        using _Type0 = CUtlLeanVectorFixedGrowable<RnMesh_t,1>;
        SCHEMA_FIELD(RnCompoundTree_t                , m_Tree                                          , 0x0) // RnCompoundTree_t
        SCHEMA_FIELD(std::int32_t                    , m_nHullBaseIndex                                , 0x18) // int32
        SCHEMA_FIELD(std::int32_t                    , m_nMeshBaseIndex                                , 0x1C) // int32
        SCHEMA_FIELD(std::int32_t                    , m_nShapeCount                                   , 0x20) // int32
        SCHEMA_FIELD(_Type0                          , m_Meshes                                        , 0x28) // CUtlLeanVectorFixedGrowable<RnMesh_t,1>
        SCHEMA_FIELD(CUtlLeanVector<RnHull_t>        , m_Hulls                                         , 0xF0) // CUtlLeanVector<RnHull_t>
        SCHEMA_FIELD(CUtlLeanVector<RnCapsule_t>     , m_Capsules                                      , 0x100) // CUtlLeanVector<RnCapsule_t>
        SCHEMA_FIELD(CUtlLeanVector<RnSphere_t>      , m_Spheres                                       , 0x110) // CUtlLeanVector<RnSphere_t>
        SCHEMA_FIELD(CUtlLeanVector<uint8>           , m_CompoundMaterialIndices                       , 0x120) // CUtlLeanVector<uint8>
        SCHEMA_FIELD(::AABB_t                        , m_Bounds                                        , 0x130) // AABB_t
        SCHEMA_FIELD(::Vector                        , m_vOrthographicAreas                            , 0x148) // Vector
        SCHEMA_FIELD(float                           , m_flSurfaceArea                                 , 0x154) // float32
        SCHEMA_FIELD(float                           , m_flVolume                                      , 0x158) // float32
    };

    // IPhysicsBodyList
    //   fields: 0
    //   size: 0x8
    class IPhysicsBodyList {
    public:
    };

    // vphysics_save_ragdoll_control_t
    //   fields: 10
    //   size: 0x38
    //   @MGetKV3ClassDefaults
    class vphysics_save_ragdoll_control_t {
    public:
        SCHEMA_FIELD(float                           , m_flMinSpringFrequency                          , 0x0) // float32
        SCHEMA_FIELD(float                           , m_flMaxSpringFrequency                          , 0x4) // float32
        SCHEMA_FIELD(float                           , m_flMaxStretch                                  , 0x8) // float32
        SCHEMA_FIELD(bool                            , m_bSolidCollisionAtZeroWeight                   , 0xC) // bool
        SCHEMA_FIELD(bool                            , m_bRequiresDynamicBodies                        , 0xD) // bool
        SCHEMA_FIELD(bool                            , m_bIgnoreTeleport                               , 0xE) // bool
        SCHEMA_FIELD(::Vector                        , m_vLinearVelocityAccumulator                    , 0x10) // Vector
        SCHEMA_FIELD(RotationVector                  , m_vAngularVelocityAccumulator                   , 0x1C) // RotationVector
        SCHEMA_FIELD(::Vector                        , m_vForceAccumulator                             , 0x28) // Vector
        SCHEMA_FIELD(std::int32_t                    , m_nBodyCount                                    , 0x34) // int32
    };

    // FeVertexMapBuild_t
    //   fields: 6
    //   size: 0x30
    //   @MGetKV3ClassDefaults
    class FeVertexMapBuild_t {
    public:
        SCHEMA_FIELD(::CUtlString                    , m_VertexMapName                                 , 0x0) // CUtlString
        SCHEMA_FIELD(std::uint32_t                   , m_nNameHash                                     , 0x8) // uint32
        SCHEMA_FIELD(::Color                         , m_Color                                         , 0xC) // Color
        SCHEMA_FIELD(float                           , m_flVolumetricSolveStrength                     , 0x10) // float32
        SCHEMA_FIELD(std::int32_t                    , m_nScaleSourceNode                              , 0x14) // int32
        SCHEMA_FIELD(CUtlVector<float32>             , m_Weights                                       , 0x18) // CUtlVector<float32>
    };

    // FeTri_t
    //   fields: 5
    //   size: 0x1C
    //   @MGetKV3ClassDefaults
    class FeTri_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , nNode                                           , 0x0) // uint16[3]
        SCHEMA_FIELD(float                           , w1                                              , 0x8) // float32
        SCHEMA_FIELD(float                           , w2                                              , 0xC) // float32
        SCHEMA_FIELD(float                           , v1x                                             , 0x10) // float32
        SCHEMA_FIELD(::Vector2D                      , v2                                              , 0x14) // Vector2D
    };

    // FeNodeReverseOffset_t
    //   fields: 3
    //   size: 0x10
    //   @MGetKV3ClassDefaults
    class FeNodeReverseOffset_t {
    public:
        SCHEMA_FIELD(::Vector                        , vOffset                                         , 0x0) // Vector
        SCHEMA_FIELD(std::uint16_t                   , nBoneCtrl                                       , 0xC) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nTargetNode                                     , 0xE) // uint16
    };

    // FeSphereRigid_t
    //   fields: 5
    //   size: 0x20
    //   @MGetKV3ClassDefaults
    class FeSphereRigid_t {
    public:
        SCHEMA_FIELD(fltx4                           , vSphere                                         , 0x0) // fltx4
        SCHEMA_FIELD(std::uint16_t                   , nNode                                           , 0x10) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nCollisionMask                                  , 0x12) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nVertexMapIndex                                 , 0x14) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nFlags                                          , 0x16) // uint16
    };

    // CovMatrix3
    //   fields: 4
    //   size: 0x18
    //   @MGetKV3ClassDefaults
    class CovMatrix3 {
    public:
        SCHEMA_FIELD(::Vector                        , m_vDiag                                         , 0x0) // Vector
        SCHEMA_FIELD(float                           , m_flXY                                          , 0xC) // float32
        SCHEMA_FIELD(float                           , m_flXZ                                          , 0x10) // float32
        SCHEMA_FIELD(float                           , m_flYZ                                          , 0x14) // float32
    };

    // FeNodeWindBase_t
    //   fields: 4
    //   size: 0x8
    //   @MGetKV3ClassDefaults
    class FeNodeWindBase_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , nNodeX0                                         , 0x0) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nNodeX1                                         , 0x2) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nNodeY0                                         , 0x4) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nNodeY1                                         , 0x6) // uint16
    };

    // PhysicsParticleId_t
    //   fields: 1
    //   size: 0x4
    class PhysicsParticleId_t {
    public:
        SCHEMA_FIELD(std::uint32_t                   , m_Value                                         , 0x0) // uint32
    };

    // IPhysicsBody
    //   fields: 0
    //   size: 0x8
    class IPhysicsBody {
    public:
    };

    // RnBlendVertex_t
    //   fields: 8
    //   size: 0x10
    //   @MGetKV3ClassDefaults
    class RnBlendVertex_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , m_nWeight0                                      , 0x0) // uint16
        SCHEMA_FIELD(std::uint16_t                   , m_nIndex0                                       , 0x2) // uint16
        SCHEMA_FIELD(std::uint16_t                   , m_nWeight1                                      , 0x4) // uint16
        SCHEMA_FIELD(std::uint16_t                   , m_nIndex1                                       , 0x6) // uint16
        SCHEMA_FIELD(std::uint16_t                   , m_nWeight2                                      , 0x8) // uint16
        SCHEMA_FIELD(std::uint16_t                   , m_nIndex2                                       , 0xA) // uint16
        SCHEMA_FIELD(std::uint16_t                   , m_nFlags                                        , 0xC) // uint16
        SCHEMA_FIELD(std::uint16_t                   , m_nTargetIndex                                  , 0xE) // uint16
    };

    // FeNodeStrayBox_t
    //   fields: 4
    //   size: 0x20
    //   @MGetKV3ClassDefaults
    class FeNodeStrayBox_t {
    public:
        SCHEMA_FIELD(::Vector                        , vMin                                            , 0x0) // Vector
        SCHEMA_FIELD(std::uint32_t                   , nFlags                                          , 0xC) // uint32
        SCHEMA_FIELD(::Vector                        , vMax                                            , 0x10) // Vector
        SCHEMA_FIELD(std::uint16_t                   , nNode                                           , 0x1C) // uint16[2]
    };

    // constraint_hingeparams_t
    //   fields: 4
    //   size: 0x40
    //   @MGetKV3ClassDefaults
    class constraint_hingeparams_t {
    public:
        SCHEMA_FIELD(VectorWS                        , worldPosition                                   , 0x0) // VectorWS
        SCHEMA_FIELD(::Vector                        , worldAxisDirection                              , 0xC) // Vector
        SCHEMA_FIELD(constraint_axislimit_t          , hingeAxis                                       , 0x18) // constraint_axislimit_t [MNotSaved]
        SCHEMA_FIELD(constraint_breakableparams_t    , constraint                                      , 0x28) // constraint_breakableparams_t [MNotSaved]
    };

    // IPhysicsParticleRope
    //   fields: 0
    //   size: 0x8
    class IPhysicsParticleRope {
    public:
    };

    // constraint_axislimit_t
    //   fields: 4
    //   size: 0x10
    class constraint_axislimit_t {
    public:
        SCHEMA_FIELD(float                           , flMinRotation                                   , 0x0) // float32
        SCHEMA_FIELD(float                           , flMaxRotation                                   , 0x4) // float32
        SCHEMA_FIELD(float                           , flMotorTargetAngSpeed                           , 0x8) // float32
        SCHEMA_FIELD(float                           , flMotorMaxTorque                                , 0xC) // float32
    };

    // RnWing_t
    //   fields: 1
    //   size: 0xC
    //   @MGetKV3ClassDefaults
    class RnWing_t {
    public:
        SCHEMA_FIELD(std::int32_t                    , m_nIndex                                        , 0x0) // int32[3]
    };

    // Dop26_t
    //   fields: 1
    //   size: 0x68
    //   @MGetKV3ClassDefaults
    class Dop26_t {
    public:
        SCHEMA_FIELD(float                           , m_flSupport                                     , 0x0) // float32[26]
    };

    // FeSimdRodConstraint_t
    //   fields: 5
    //   size: 0x50
    //   @MGetKV3ClassDefaults
    class FeSimdRodConstraint_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , nNode                                           , 0x0) // uint16[4][2]
        SCHEMA_FIELD(fltx4                           , f4MaxDist                                       , 0x10) // fltx4
        SCHEMA_FIELD(fltx4                           , f4MinDist                                       , 0x20) // fltx4
        SCHEMA_FIELD(fltx4                           , f4Weight0                                       , 0x30) // fltx4
        SCHEMA_FIELD(fltx4                           , f4RelaxationFactor                              , 0x40) // fltx4
    };

    // RnCapsule_t
    //   fields: 2
    //   size: 0x1C
    //   @MGetKV3ClassDefaults
    class RnCapsule_t {
    public:
        SCHEMA_FIELD(::Vector                        , m_vCenter                                       , 0x0) // Vector[2]
        SCHEMA_FIELD(float                           , m_flRadius                                      , 0x18) // float32
    };

    // FeKelagerBend2_t
    //   fields: 4
    //   size: 0x18
    //   @MGetKV3ClassDefaults
    class FeKelagerBend2_t {
    public:
        SCHEMA_FIELD(float                           , flWeight                                        , 0x0) // float32[3]
        SCHEMA_FIELD(float                           , flHeight0                                       , 0xC) // float32
        SCHEMA_FIELD(std::uint16_t                   , nNode                                           , 0x10) // uint16[3]
        SCHEMA_FIELD(std::uint16_t                   , nReserved                                       , 0x16) // uint16
    };

    // RnSoftbodySpring_t
    //   fields: 2
    //   size: 0x8
    //   @MGetKV3ClassDefaults
    class RnSoftbodySpring_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , m_nParticle                                     , 0x0) // uint16[2]
        SCHEMA_FIELD(float                           , m_flLength                                      , 0x4) // float32
    };

    // FeTaperedCapsuleRigid_t
    //   fields: 5
    //   size: 0x30
    //   @MGetKV3ClassDefaults
    class FeTaperedCapsuleRigid_t {
    public:
        SCHEMA_FIELD(fltx4                           , vSphere                                         , 0x0) // fltx4[2]
        SCHEMA_FIELD(std::uint16_t                   , nNode                                           , 0x20) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nCollisionMask                                  , 0x22) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nVertexMapIndex                                 , 0x24) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nFlags                                          , 0x26) // uint16
    };

    // FourVectors2D
    //   fields: 2
    //   size: 0x20
    //   @MGetKV3ClassDefaults
    class FourVectors2D {
    public:
        SCHEMA_FIELD(fltx4                           , x                                               , 0x0) // fltx4
        SCHEMA_FIELD(fltx4                           , y                                               , 0x10) // fltx4
    };

    // FeSimdNodeBase_t
    //   fields: 7
    //   size: 0x70
    //   @MGetKV3ClassDefaults
    class FeSimdNodeBase_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , nNode                                           , 0x0) // uint16[4]
        SCHEMA_FIELD(std::uint16_t                   , nNodeX0                                         , 0x8) // uint16[4]
        SCHEMA_FIELD(std::uint16_t                   , nNodeX1                                         , 0x10) // uint16[4]
        SCHEMA_FIELD(std::uint16_t                   , nNodeY0                                         , 0x18) // uint16[4]
        SCHEMA_FIELD(std::uint16_t                   , nNodeY1                                         , 0x20) // uint16[4]
        SCHEMA_FIELD(std::uint16_t                   , nDummy                                          , 0x28) // uint16[4]
        SCHEMA_FIELD(::resourcesystem::FourQuaternions, qAdjust                                         , 0x30) // FourQuaternions
    };

    // VertexPositionColor_t
    //   fields: 1
    //   size: 0x10
    class VertexPositionColor_t {
    public:
        SCHEMA_FIELD(::Vector                        , m_vPosition                                     , 0x0) // Vector
    };

    // FePrism_t
    //   fields: 2
    //   size: 0x10
    //   @MGetKV3ClassDefaults
    class FePrism_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , nNode                                           , 0x0) // uint16[6]
        SCHEMA_FIELD(float                           , flVolume                                        , 0xC) // float32
    };

    // FeSoftParent_t
    //   fields: 2
    //   size: 0x8
    //   @MGetKV3ClassDefaults
    class FeSoftParent_t {
    public:
        SCHEMA_FIELD(std::int32_t                    , nParent                                         , 0x0) // int32
        SCHEMA_FIELD(float                           , flAlpha                                         , 0x4) // float32
    };

    // FeCtrlSoftOffset_t
    //   fields: 4
    //   size: 0x14
    //   @MGetKV3ClassDefaults
    class FeCtrlSoftOffset_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , nCtrlParent                                     , 0x0) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nCtrlChild                                      , 0x2) // uint16
        SCHEMA_FIELD(::Vector                        , vOffset                                         , 0x4) // Vector
        SCHEMA_FIELD(float                           , flAlpha                                         , 0x10) // float32
    };

    // vphysics_save_cphysicsbody_t
    //   fields: 1
    //   size: 0xE8
    //   @MGetKV3ClassDefaults
    class vphysics_save_cphysicsbody_t {
    public:
        SCHEMA_FIELD(std::uint64_t                   , m_nOldPointer                                   , 0xE0) // uint64
    };

    // IPhysicsJoint
    //   fields: 0
    //   size: 0x8
    class IPhysicsJoint {
    public:
    };

    // FeSimdTri_t
    //   fields: 5
    //   size: 0x80
    //   @MGetKV3ClassDefaults
    class FeSimdTri_t {
    public:
        SCHEMA_FIELD(std::uint32_t                   , nNode                                           , 0x0) // uint32[4][3]
        SCHEMA_FIELD(fltx4                           , w1                                              , 0x30) // fltx4
        SCHEMA_FIELD(fltx4                           , w2                                              , 0x40) // fltx4
        SCHEMA_FIELD(fltx4                           , v1x                                             , 0x50) // fltx4
        SCHEMA_FIELD(FourVectors2D                   , v2                                              , 0x60) // FourVectors2D
    };

    // FeRigidColliderIndices_t
    //   fields: 5
    //   size: 0xA
    //   @MGetKV3ClassDefaults
    class FeRigidColliderIndices_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , m_nTaperedCapsuleRigidIndex                     , 0x0) // uint16
        SCHEMA_FIELD(std::uint16_t                   , m_nSphereRigidIndex                             , 0x2) // uint16
        SCHEMA_FIELD(std::uint16_t                   , m_nBoxRigidIndex                                , 0x4) // uint16
        SCHEMA_FIELD(std::uint16_t                   , m_nSDFRigidIndex                                , 0x6) // uint16
        SCHEMA_FIELD(std::uint16_t                   , m_nCollisionPlaneIndex                          , 0x8) // uint16
    };

    // FeRodConstraint_t
    //   fields: 5
    //   size: 0x14
    //   @MGetKV3ClassDefaults
    class FeRodConstraint_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , nNode                                           , 0x0) // uint16[2]
        SCHEMA_FIELD(float                           , flMaxDist                                       , 0x4) // float32
        SCHEMA_FIELD(float                           , flMinDist                                       , 0x8) // float32
        SCHEMA_FIELD(float                           , flWeight0                                       , 0xC) // float32
        SCHEMA_FIELD(float                           , flRelaxationFactor                              , 0x10) // float32
    };

    // FeSDFRigid_t
    //   fields: 11
    //   size: 0x50
    //   @MGetKV3ClassDefaults
    class FeSDFRigid_t {
    public:
        SCHEMA_FIELD(::Vector                        , vLocalMin                                       , 0x0) // Vector
        SCHEMA_FIELD(::Vector                        , vLocalMax                                       , 0xC) // Vector
        SCHEMA_FIELD(float                           , flBounciness                                    , 0x18) // float32
        SCHEMA_FIELD(std::uint16_t                   , nNode                                           , 0x1C) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nCollisionMask                                  , 0x1E) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nVertexMapIndex                                 , 0x20) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nFlags                                          , 0x22) // uint16
        SCHEMA_FIELD(CUtlVector<float32>             , m_Distances                                     , 0x28) // CUtlVector<float32>
        SCHEMA_FIELD(std::int32_t                    , m_nWidth                                        , 0x40) // int32
        SCHEMA_FIELD(std::int32_t                    , m_nHeight                                       , 0x44) // int32
        SCHEMA_FIELD(std::int32_t                    , m_nDepth                                        , 0x48) // int32
    };

    // RnFace_t
    //   fields: 1
    //   size: 0x1
    //   @MGetKV3ClassDefaults
    class RnFace_t {
    public:
        SCHEMA_FIELD(std::uint8_t                    , m_nEdge                                         , 0x0) // uint8
    };

    // constraint_breakableparams_t
    //   fields: 5
    //   size: 0x18
    class constraint_breakableparams_t {
    public:
        SCHEMA_FIELD(float                           , strength                                        , 0x0) // float32
        SCHEMA_FIELD(float                           , forceLimit                                      , 0x4) // float32
        SCHEMA_FIELD(float                           , torqueLimit                                     , 0x8) // float32
        SCHEMA_FIELD(float                           , bodyMassScale                                   , 0xC) // float32[2]
        SCHEMA_FIELD(bool                            , isActive                                        , 0x14) // bool
    };

    // FeHingeLimit_t
    //   fields: 6
    //   size: 0x20
    //   @MGetKV3ClassDefaults
    class FeHingeLimit_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , nNode                                           , 0x0) // uint16[6]
        SCHEMA_FIELD(std::uint32_t                   , nFlags                                          , 0xC) // uint32
        SCHEMA_FIELD(float                           , flWeight4                                       , 0x10) // float32
        SCHEMA_FIELD(float                           , flWeight5                                       , 0x14) // float32
        SCHEMA_FIELD(float                           , flAngleCenter                                   , 0x18) // float32
        SCHEMA_FIELD(float                           , flAngleExtents                                  , 0x1C) // float32
    };

    // FeStiffHingeBuild_t
    //   fields: 4
    //   size: 0x1C
    //   @MGetKV3ClassDefaults
    class FeStiffHingeBuild_t {
    public:
        SCHEMA_FIELD(float                           , flMaxAngle                                      , 0x0) // float32
        SCHEMA_FIELD(float                           , flStrength                                      , 0x4) // float32
        SCHEMA_FIELD(float                           , flMotionBias                                    , 0x8) // float32[3]
        SCHEMA_FIELD(std::uint16_t                   , nNode                                           , 0x14) // uint16[3]
    };

    // FeBoxRigid_t
    //   fields: 6
    //   size: 0x40
    //   @MGetKV3ClassDefaults
    class FeBoxRigid_t {
    public:
        SCHEMA_FIELD(CTransform                      , tmFrame2                                        , 0x0) // CTransform
        SCHEMA_FIELD(std::uint16_t                   , nNode                                           , 0x20) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nCollisionMask                                  , 0x22) // uint16
        SCHEMA_FIELD(::Vector                        , vSize                                           , 0x24) // Vector
        SCHEMA_FIELD(std::uint16_t                   , nVertexMapIndex                                 , 0x30) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nFlags                                          , 0x32) // uint16
    };

    // FeNodeIntegrator_t
    //   fields: 4
    //   size: 0x10
    //   @MGetKV3ClassDefaults
    class FeNodeIntegrator_t {
    public:
        SCHEMA_FIELD(float                           , flPointDamping                                  , 0x0) // float32
        SCHEMA_FIELD(float                           , flAnimationForceAttraction                      , 0x4) // float32
        SCHEMA_FIELD(float                           , flAnimationVertexAttraction                     , 0x8) // float32
        SCHEMA_FIELD(float                           , flGravity                                       , 0xC) // float32
    };

    // CFeJiggleBone
    //   fields: 35
    //   size: 0x9C
    //   @MGetKV3ClassDefaults
    class CFeJiggleBone {
    public:
        SCHEMA_FIELD(std::uint32_t                   , m_nFlags                                        , 0x0) // uint32
        SCHEMA_FIELD(float                           , m_flLength                                      , 0x4) // float32
        SCHEMA_FIELD(float                           , m_flTipMass                                     , 0x8) // float32
        SCHEMA_FIELD(float                           , m_flYawStiffness                                , 0xC) // float32
        SCHEMA_FIELD(float                           , m_flYawDamping                                  , 0x10) // float32
        SCHEMA_FIELD(float                           , m_flPitchStiffness                              , 0x14) // float32
        SCHEMA_FIELD(float                           , m_flPitchDamping                                , 0x18) // float32
        SCHEMA_FIELD(float                           , m_flAlongStiffness                              , 0x1C) // float32
        SCHEMA_FIELD(float                           , m_flAlongDamping                                , 0x20) // float32
        SCHEMA_FIELD(float                           , m_flAngleLimit                                  , 0x24) // float32
        SCHEMA_FIELD(float                           , m_flMinYaw                                      , 0x28) // float32
        SCHEMA_FIELD(float                           , m_flMaxYaw                                      , 0x2C) // float32
        SCHEMA_FIELD(float                           , m_flYawFriction                                 , 0x30) // float32
        SCHEMA_FIELD(float                           , m_flYawBounce                                   , 0x34) // float32
        SCHEMA_FIELD(float                           , m_flMinPitch                                    , 0x38) // float32
        SCHEMA_FIELD(float                           , m_flMaxPitch                                    , 0x3C) // float32
        SCHEMA_FIELD(float                           , m_flPitchFriction                               , 0x40) // float32
        SCHEMA_FIELD(float                           , m_flPitchBounce                                 , 0x44) // float32
        SCHEMA_FIELD(float                           , m_flBaseMass                                    , 0x48) // float32
        SCHEMA_FIELD(float                           , m_flBaseStiffness                               , 0x4C) // float32
        SCHEMA_FIELD(float                           , m_flBaseDamping                                 , 0x50) // float32
        SCHEMA_FIELD(float                           , m_flBaseMinLeft                                 , 0x54) // float32
        SCHEMA_FIELD(float                           , m_flBaseMaxLeft                                 , 0x58) // float32
        SCHEMA_FIELD(float                           , m_flBaseLeftFriction                            , 0x5C) // float32
        SCHEMA_FIELD(float                           , m_flBaseMinUp                                   , 0x60) // float32
        SCHEMA_FIELD(float                           , m_flBaseMaxUp                                   , 0x64) // float32
        SCHEMA_FIELD(float                           , m_flBaseUpFriction                              , 0x68) // float32
        SCHEMA_FIELD(float                           , m_flBaseMinForward                              , 0x6C) // float32
        SCHEMA_FIELD(float                           , m_flBaseMaxForward                              , 0x70) // float32
        SCHEMA_FIELD(float                           , m_flBaseForwardFriction                         , 0x74) // float32
        SCHEMA_FIELD(float                           , m_flRadius0                                     , 0x78) // float32
        SCHEMA_FIELD(float                           , m_flRadius1                                     , 0x7C) // float32
        SCHEMA_FIELD(::Vector                        , m_vPoint0                                       , 0x80) // Vector
        SCHEMA_FIELD(::Vector                        , m_vPoint1                                       , 0x8C) // Vector
        SCHEMA_FIELD(std::uint16_t                   , m_nCollisionMask                                , 0x98) // uint16
    };

    // FeFollowNode_t
    //   fields: 3
    //   size: 0x8
    //   @MGetKV3ClassDefaults
    class FeFollowNode_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , nParentNode                                     , 0x0) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nChildNode                                      , 0x2) // uint16
        SCHEMA_FIELD(float                           , flWeight                                        , 0x4) // float32
    };

    // FeAxialEdgeBend_t
    //   fields: 5
    //   size: 0x28
    //   @MGetKV3ClassDefaults
    class FeAxialEdgeBend_t {
    public:
        SCHEMA_FIELD(float                           , te                                              , 0x0) // float32
        SCHEMA_FIELD(float                           , tv                                              , 0x4) // float32
        SCHEMA_FIELD(float                           , flDist                                          , 0x8) // float32
        SCHEMA_FIELD(float                           , flWeight                                        , 0xC) // float32[4]
        SCHEMA_FIELD(std::uint16_t                   , nNode                                           , 0x1C) // uint16[6]
    };

    // OldFeEdge_t
    //   fields: 12
    //   size: 0x48
    //   @MGetKV3ClassDefaults
    class OldFeEdge_t {
    public:
        SCHEMA_FIELD(float                           , m_flK                                           , 0x0) // float32[3]
        SCHEMA_FIELD(float                           , invA                                            , 0xC) // float32
        SCHEMA_FIELD(float                           , t                                               , 0x10) // float32
        SCHEMA_FIELD(float                           , flThetaRelaxed                                  , 0x14) // float32
        SCHEMA_FIELD(float                           , flThetaFactor                                   , 0x18) // float32
        SCHEMA_FIELD(float                           , c01                                             , 0x1C) // float32
        SCHEMA_FIELD(float                           , c02                                             , 0x20) // float32
        SCHEMA_FIELD(float                           , c03                                             , 0x24) // float32
        SCHEMA_FIELD(float                           , c04                                             , 0x28) // float32
        SCHEMA_FIELD(float                           , flAxialModelDist                                , 0x2C) // float32
        SCHEMA_FIELD(float                           , flAxialModelWeights                             , 0x30) // float32[4]
        SCHEMA_FIELD(std::uint16_t                   , m_nNode                                         , 0x40) // uint16[4]
    };

    // FeSimdSpringIntegrator_t
    //   fields: 5
    //   size: 0x50
    //   @MGetKV3ClassDefaults
    class FeSimdSpringIntegrator_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , nNode                                           , 0x0) // uint16[4][2]
        SCHEMA_FIELD(fltx4                           , flSpringRestLength                              , 0x10) // fltx4
        SCHEMA_FIELD(fltx4                           , flSpringConstant                                , 0x20) // fltx4
        SCHEMA_FIELD(fltx4                           , flSpringDamping                                 , 0x30) // fltx4
        SCHEMA_FIELD(fltx4                           , flNodeWeight0                                   , 0x40) // fltx4
    };

    // IPhysicsMotionController
    //   fields: 0
    //   size: 0x8
    class IPhysicsMotionController {
    public:
    };

    // FeVertexMapDesc_t
    //   fields: 12
    //   size: 0x38
    //   @MGetKV3ClassDefaults
    class FeVertexMapDesc_t {
    public:
        SCHEMA_FIELD(::CUtlString                    , sName                                           , 0x0) // CUtlString
        SCHEMA_FIELD(std::uint32_t                   , nNameHash                                       , 0x8) // uint32
        SCHEMA_FIELD(std::uint32_t                   , nColor                                          , 0xC) // uint32
        SCHEMA_FIELD(std::uint32_t                   , nFlags                                          , 0x10) // uint32
        SCHEMA_FIELD(std::uint16_t                   , nVertexBase                                     , 0x14) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nVertexCount                                    , 0x16) // uint16
        SCHEMA_FIELD(std::uint32_t                   , nMapOffset                                      , 0x18) // uint32
        SCHEMA_FIELD(std::uint32_t                   , nNodeListOffset                                 , 0x1C) // uint32
        SCHEMA_FIELD(::Vector                        , vCenterOfMass                                   , 0x20) // Vector
        SCHEMA_FIELD(float                           , flVolumetricSolveStrength                       , 0x2C) // float32
        SCHEMA_FIELD(std::int16_t                    , nScaleSourceNode                                , 0x30) // int16
        SCHEMA_FIELD(std::uint16_t                   , nNodeListCount                                  , 0x32) // uint16
    };

    // CFeVertexMapBuildArray
    //   fields: 1
    //   size: 0x18
    //   @MGetKV3ClassDefaults
    class CFeVertexMapBuildArray {
    public:
        SCHEMA_FIELD(CUtlVector<FeVertexMapBuild_t*> , m_Array                                         , 0x0) // CUtlVector<FeVertexMapBuild_t*>
    };

    // FeBoneMergeLink_t
    //   fields: 2
    //   size: 0x8
    //   @MGetKV3ClassDefaults
    class FeBoneMergeLink_t {
    public:
        SCHEMA_FIELD(std::uint32_t                   , m_nParentHash                                   , 0x0) // uint32
        SCHEMA_FIELD(std::uint16_t                   , m_nChildNode                                    , 0x4) // uint16
    };

    // CFeIndexedJiggleBone
    //   fields: 3
    //   size: 0xA4
    //   @MGetKV3ClassDefaults
    class CFeIndexedJiggleBone {
    public:
        SCHEMA_FIELD(std::uint32_t                   , m_nNode                                         , 0x0) // uint32
        SCHEMA_FIELD(std::uint32_t                   , m_nJiggleParent                                 , 0x4) // uint32
        SCHEMA_FIELD(CFeJiggleBone                   , m_jiggleBone                                    , 0x8) // CFeJiggleBone
    };

    // FeBuildBoxRigid_t
    //   fields: 3
    //   size: 0x50
    //   @MGetKV3ClassDefaults
    class FeBuildBoxRigid_t {
    public:
        SCHEMA_FIELD(std::int32_t                    , m_nPriority                                     , 0x40) // int32
        SCHEMA_FIELD(std::uint32_t                   , m_nVertexMapHash                                , 0x44) // uint32
        SCHEMA_FIELD(std::uint32_t                   , m_nAntitunnelGroupBits                          , 0x48) // uint32
    };

    // FeNodeBase_t
    //   fields: 7
    //   size: 0x20
    //   @MGetKV3ClassDefaults
    class FeNodeBase_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , nNode                                           , 0x0) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nDummy                                          , 0x2) // uint16[3]
        SCHEMA_FIELD(std::uint16_t                   , nNodeX0                                         , 0x8) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nNodeX1                                         , 0xA) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nNodeY0                                         , 0xC) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nNodeY1                                         , 0xE) // uint16
        SCHEMA_FIELD(QuaternionStorage               , qAdjust                                         , 0x10) // QuaternionStorage
    };

    // FeTreeChildren_t
    //   fields: 1
    //   size: 0x4
    //   @MGetKV3ClassDefaults
    class FeTreeChildren_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , nChild                                          , 0x0) // uint16[2]
    };

    // FeBandBendLimit_t
    //   fields: 3
    //   size: 0x14
    //   @MGetKV3ClassDefaults
    class FeBandBendLimit_t {
    public:
        SCHEMA_FIELD(float                           , flDistMin                                       , 0x0) // float32
        SCHEMA_FIELD(float                           , flDistMax                                       , 0x4) // float32
        SCHEMA_FIELD(std::uint16_t                   , nNode                                           , 0x8) // uint16[6]
    };

    // FeCollisionPlane_t
    //   fields: 4
    //   size: 0x18
    //   @MGetKV3ClassDefaults
    class FeCollisionPlane_t {
    public:
        SCHEMA_FIELD(std::uint16_t                   , nCtrlParent                                     , 0x0) // uint16
        SCHEMA_FIELD(std::uint16_t                   , nChildNode                                      , 0x2) // uint16
        SCHEMA_FIELD(RnPlane_t                       , m_Plane                                         , 0x4) // RnPlane_t
        SCHEMA_FIELD(float                           , flStrength                                      , 0x14) // float32
    };

} // namespace vphysics2
